// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: aserto/directory/reader/v3/reader.proto

package reader

import (
	v3 "github.com/aserto-dev/go-directory/aserto/directory/common/v3"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetObjectRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// object type name (lc-string)
	ObjectType string `protobuf:"bytes,1,opt,name=object_type,json=objectType,proto3" json:"object_type,omitempty"`
	// object identifier (cs-string)
	ObjectId string `protobuf:"bytes,2,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	// materialize the object relations objects
	WithRelations bool `protobuf:"varint,3,opt,name=with_relations,json=withRelations,proto3" json:"with_relations,omitempty"`
	// pagination request
	Page          *v3.PaginationRequest `protobuf:"bytes,9,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetObjectRequest) Reset() {
	*x = GetObjectRequest{}
	mi := &file_aserto_directory_reader_v3_reader_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObjectRequest) ProtoMessage() {}

func (x *GetObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_directory_reader_v3_reader_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObjectRequest.ProtoReflect.Descriptor instead.
func (*GetObjectRequest) Descriptor() ([]byte, []int) {
	return file_aserto_directory_reader_v3_reader_proto_rawDescGZIP(), []int{0}
}

func (x *GetObjectRequest) GetObjectType() string {
	if x != nil {
		return x.ObjectType
	}
	return ""
}

func (x *GetObjectRequest) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *GetObjectRequest) GetWithRelations() bool {
	if x != nil {
		return x.WithRelations
	}
	return false
}

func (x *GetObjectRequest) GetPage() *v3.PaginationRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type GetObjectResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// object instance
	Result *v3.Object `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	// object relations
	Relations []*v3.Relation `protobuf:"bytes,4,rep,name=relations,proto3" json:"relations,omitempty"`
	// pagination response
	Page          *v3.PaginationResponse `protobuf:"bytes,9,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetObjectResponse) Reset() {
	*x = GetObjectResponse{}
	mi := &file_aserto_directory_reader_v3_reader_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetObjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObjectResponse) ProtoMessage() {}

func (x *GetObjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_directory_reader_v3_reader_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObjectResponse.ProtoReflect.Descriptor instead.
func (*GetObjectResponse) Descriptor() ([]byte, []int) {
	return file_aserto_directory_reader_v3_reader_proto_rawDescGZIP(), []int{1}
}

func (x *GetObjectResponse) GetResult() *v3.Object {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *GetObjectResponse) GetRelations() []*v3.Relation {
	if x != nil {
		return x.Relations
	}
	return nil
}

func (x *GetObjectResponse) GetPage() *v3.PaginationResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

type GetObjectManyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// object identifier list
	Param         []*v3.ObjectIdentifier `protobuf:"bytes,1,rep,name=param,proto3" json:"param,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetObjectManyRequest) Reset() {
	*x = GetObjectManyRequest{}
	mi := &file_aserto_directory_reader_v3_reader_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetObjectManyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObjectManyRequest) ProtoMessage() {}

func (x *GetObjectManyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_directory_reader_v3_reader_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObjectManyRequest.ProtoReflect.Descriptor instead.
func (*GetObjectManyRequest) Descriptor() ([]byte, []int) {
	return file_aserto_directory_reader_v3_reader_proto_rawDescGZIP(), []int{2}
}

func (x *GetObjectManyRequest) GetParam() []*v3.ObjectIdentifier {
	if x != nil {
		return x.Param
	}
	return nil
}

type GetObjectManyResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// array of object instances
	Results       []*v3.Object `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetObjectManyResponse) Reset() {
	*x = GetObjectManyResponse{}
	mi := &file_aserto_directory_reader_v3_reader_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetObjectManyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObjectManyResponse) ProtoMessage() {}

func (x *GetObjectManyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_directory_reader_v3_reader_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObjectManyResponse.ProtoReflect.Descriptor instead.
func (*GetObjectManyResponse) Descriptor() ([]byte, []int) {
	return file_aserto_directory_reader_v3_reader_proto_rawDescGZIP(), []int{3}
}

func (x *GetObjectManyResponse) GetResults() []*v3.Object {
	if x != nil {
		return x.Results
	}
	return nil
}

type GetObjectsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// object type name (lc-string)
	ObjectType string `protobuf:"bytes,1,opt,name=object_type,json=objectType,proto3" json:"object_type,omitempty"`
	// pagination request
	Page          *v3.PaginationRequest `protobuf:"bytes,9,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetObjectsRequest) Reset() {
	*x = GetObjectsRequest{}
	mi := &file_aserto_directory_reader_v3_reader_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetObjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObjectsRequest) ProtoMessage() {}

func (x *GetObjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_directory_reader_v3_reader_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObjectsRequest.ProtoReflect.Descriptor instead.
func (*GetObjectsRequest) Descriptor() ([]byte, []int) {
	return file_aserto_directory_reader_v3_reader_proto_rawDescGZIP(), []int{4}
}

func (x *GetObjectsRequest) GetObjectType() string {
	if x != nil {
		return x.ObjectType
	}
	return ""
}

func (x *GetObjectsRequest) GetPage() *v3.PaginationRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type GetObjectsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// array of object instances
	Results []*v3.Object `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	// pagination response
	Page          *v3.PaginationResponse `protobuf:"bytes,9,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetObjectsResponse) Reset() {
	*x = GetObjectsResponse{}
	mi := &file_aserto_directory_reader_v3_reader_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetObjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObjectsResponse) ProtoMessage() {}

func (x *GetObjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_directory_reader_v3_reader_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObjectsResponse.ProtoReflect.Descriptor instead.
func (*GetObjectsResponse) Descriptor() ([]byte, []int) {
	return file_aserto_directory_reader_v3_reader_proto_rawDescGZIP(), []int{5}
}

func (x *GetObjectsResponse) GetResults() []*v3.Object {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *GetObjectsResponse) GetPage() *v3.PaginationResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

type GetRelationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// object type
	ObjectType string `protobuf:"bytes,1,opt,name=object_type,json=objectType,proto3" json:"object_type,omitempty"`
	// object identifier
	ObjectId string `protobuf:"bytes,2,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	// relation name
	Relation string `protobuf:"bytes,3,opt,name=relation,proto3" json:"relation,omitempty"`
	// subject type
	SubjectType string `protobuf:"bytes,4,opt,name=subject_type,json=subjectType,proto3" json:"subject_type,omitempty"`
	// subject identifier
	SubjectId string `protobuf:"bytes,5,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	// optional subject relation name
	SubjectRelation string `protobuf:"bytes,6,opt,name=subject_relation,json=subjectRelation,proto3" json:"subject_relation,omitempty"`
	// materialize relation objects
	WithObjects   bool `protobuf:"varint,7,opt,name=with_objects,json=withObjects,proto3" json:"with_objects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRelationRequest) Reset() {
	*x = GetRelationRequest{}
	mi := &file_aserto_directory_reader_v3_reader_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRelationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRelationRequest) ProtoMessage() {}

func (x *GetRelationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_directory_reader_v3_reader_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRelationRequest.ProtoReflect.Descriptor instead.
func (*GetRelationRequest) Descriptor() ([]byte, []int) {
	return file_aserto_directory_reader_v3_reader_proto_rawDescGZIP(), []int{6}
}

func (x *GetRelationRequest) GetObjectType() string {
	if x != nil {
		return x.ObjectType
	}
	return ""
}

func (x *GetRelationRequest) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *GetRelationRequest) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

func (x *GetRelationRequest) GetSubjectType() string {
	if x != nil {
		return x.SubjectType
	}
	return ""
}

func (x *GetRelationRequest) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *GetRelationRequest) GetSubjectRelation() string {
	if x != nil {
		return x.SubjectRelation
	}
	return ""
}

func (x *GetRelationRequest) GetWithObjects() bool {
	if x != nil {
		return x.WithObjects
	}
	return false
}

type GetRelationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// relation instance
	Result *v3.Relation `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	// map of materialized relation objects
	Objects       map[string]*v3.Object `protobuf:"bytes,2,rep,name=objects,proto3" json:"objects,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRelationResponse) Reset() {
	*x = GetRelationResponse{}
	mi := &file_aserto_directory_reader_v3_reader_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRelationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRelationResponse) ProtoMessage() {}

func (x *GetRelationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_directory_reader_v3_reader_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRelationResponse.ProtoReflect.Descriptor instead.
func (*GetRelationResponse) Descriptor() ([]byte, []int) {
	return file_aserto_directory_reader_v3_reader_proto_rawDescGZIP(), []int{7}
}

func (x *GetRelationResponse) GetResult() *v3.Relation {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *GetRelationResponse) GetObjects() map[string]*v3.Object {
	if x != nil {
		return x.Objects
	}
	return nil
}

type GetRelationsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// object type
	ObjectType string `protobuf:"bytes,1,opt,name=object_type,json=objectType,proto3" json:"object_type,omitempty"`
	// object identifier
	ObjectId string `protobuf:"bytes,2,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	// relation name
	Relation string `protobuf:"bytes,3,opt,name=relation,proto3" json:"relation,omitempty"`
	// subject type
	SubjectType string `protobuf:"bytes,4,opt,name=subject_type,json=subjectType,proto3" json:"subject_type,omitempty"`
	// subject identifier
	SubjectId string `protobuf:"bytes,5,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	// optional subject relation name
	SubjectRelation string `protobuf:"bytes,6,opt,name=subject_relation,json=subjectRelation,proto3" json:"subject_relation,omitempty"`
	// materialize relation objects
	WithObjects bool `protobuf:"varint,7,opt,name=with_objects,json=withObjects,proto3" json:"with_objects,omitempty"`
	// only return relations that do not have a subject relation.
	WithEmptySubjectRelation bool `protobuf:"varint,8,opt,name=with_empty_subject_relation,json=withEmptySubjectRelation,proto3" json:"with_empty_subject_relation,omitempty"`
	// pagination request
	Page          *v3.PaginationRequest `protobuf:"bytes,9,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRelationsRequest) Reset() {
	*x = GetRelationsRequest{}
	mi := &file_aserto_directory_reader_v3_reader_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRelationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRelationsRequest) ProtoMessage() {}

func (x *GetRelationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_directory_reader_v3_reader_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRelationsRequest.ProtoReflect.Descriptor instead.
func (*GetRelationsRequest) Descriptor() ([]byte, []int) {
	return file_aserto_directory_reader_v3_reader_proto_rawDescGZIP(), []int{8}
}

func (x *GetRelationsRequest) GetObjectType() string {
	if x != nil {
		return x.ObjectType
	}
	return ""
}

func (x *GetRelationsRequest) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *GetRelationsRequest) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

func (x *GetRelationsRequest) GetSubjectType() string {
	if x != nil {
		return x.SubjectType
	}
	return ""
}

func (x *GetRelationsRequest) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *GetRelationsRequest) GetSubjectRelation() string {
	if x != nil {
		return x.SubjectRelation
	}
	return ""
}

func (x *GetRelationsRequest) GetWithObjects() bool {
	if x != nil {
		return x.WithObjects
	}
	return false
}

func (x *GetRelationsRequest) GetWithEmptySubjectRelation() bool {
	if x != nil {
		return x.WithEmptySubjectRelation
	}
	return false
}

func (x *GetRelationsRequest) GetPage() *v3.PaginationRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type GetRelationsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// array of relation instances
	Results []*v3.Relation `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	// map of materialized relation objects
	Objects map[string]*v3.Object `protobuf:"bytes,2,rep,name=objects,proto3" json:"objects,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// pagination response
	Page          *v3.PaginationResponse `protobuf:"bytes,9,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRelationsResponse) Reset() {
	*x = GetRelationsResponse{}
	mi := &file_aserto_directory_reader_v3_reader_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRelationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRelationsResponse) ProtoMessage() {}

func (x *GetRelationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_directory_reader_v3_reader_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRelationsResponse.ProtoReflect.Descriptor instead.
func (*GetRelationsResponse) Descriptor() ([]byte, []int) {
	return file_aserto_directory_reader_v3_reader_proto_rawDescGZIP(), []int{9}
}

func (x *GetRelationsResponse) GetResults() []*v3.Relation {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *GetRelationsResponse) GetObjects() map[string]*v3.Object {
	if x != nil {
		return x.Objects
	}
	return nil
}

func (x *GetRelationsResponse) GetPage() *v3.PaginationResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

type CheckRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// object type
	ObjectType string `protobuf:"bytes,1,opt,name=object_type,json=objectType,proto3" json:"object_type,omitempty"`
	// object identifier
	ObjectId string `protobuf:"bytes,2,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	// relation name
	Relation string `protobuf:"bytes,3,opt,name=relation,proto3" json:"relation,omitempty"`
	// subject type
	SubjectType string `protobuf:"bytes,4,opt,name=subject_type,json=subjectType,proto3" json:"subject_type,omitempty"`
	// subject identifier
	SubjectId string `protobuf:"bytes,5,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	// collect trace information
	Trace         bool `protobuf:"varint,7,opt,name=trace,proto3" json:"trace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRequest) Reset() {
	*x = CheckRequest{}
	mi := &file_aserto_directory_reader_v3_reader_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRequest) ProtoMessage() {}

func (x *CheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_directory_reader_v3_reader_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRequest.ProtoReflect.Descriptor instead.
func (*CheckRequest) Descriptor() ([]byte, []int) {
	return file_aserto_directory_reader_v3_reader_proto_rawDescGZIP(), []int{10}
}

func (x *CheckRequest) GetObjectType() string {
	if x != nil {
		return x.ObjectType
	}
	return ""
}

func (x *CheckRequest) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *CheckRequest) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

func (x *CheckRequest) GetSubjectType() string {
	if x != nil {
		return x.SubjectType
	}
	return ""
}

func (x *CheckRequest) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *CheckRequest) GetTrace() bool {
	if x != nil {
		return x.Trace
	}
	return false
}

type CheckResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// check result
	Check bool `protobuf:"varint,1,opt,name=check,proto3" json:"check,omitempty"`
	// trace information
	Trace []string `protobuf:"bytes,2,rep,name=trace,proto3" json:"trace,omitempty"`
	// context
	Context       *structpb.Struct `protobuf:"bytes,3,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckResponse) Reset() {
	*x = CheckResponse{}
	mi := &file_aserto_directory_reader_v3_reader_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResponse) ProtoMessage() {}

func (x *CheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_directory_reader_v3_reader_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResponse.ProtoReflect.Descriptor instead.
func (*CheckResponse) Descriptor() ([]byte, []int) {
	return file_aserto_directory_reader_v3_reader_proto_rawDescGZIP(), []int{11}
}

func (x *CheckResponse) GetCheck() bool {
	if x != nil {
		return x.Check
	}
	return false
}

func (x *CheckResponse) GetTrace() []string {
	if x != nil {
		return x.Trace
	}
	return nil
}

func (x *CheckResponse) GetContext() *structpb.Struct {
	if x != nil {
		return x.Context
	}
	return nil
}

// EXPERIMENTAL
type ChecksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Default       *CheckRequest          `protobuf:"bytes,1,opt,name=default,proto3" json:"default,omitempty"`
	Checks        []*CheckRequest        `protobuf:"bytes,2,rep,name=checks,proto3" json:"checks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChecksRequest) Reset() {
	*x = ChecksRequest{}
	mi := &file_aserto_directory_reader_v3_reader_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChecksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChecksRequest) ProtoMessage() {}

func (x *ChecksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_directory_reader_v3_reader_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChecksRequest.ProtoReflect.Descriptor instead.
func (*ChecksRequest) Descriptor() ([]byte, []int) {
	return file_aserto_directory_reader_v3_reader_proto_rawDescGZIP(), []int{12}
}

func (x *ChecksRequest) GetDefault() *CheckRequest {
	if x != nil {
		return x.Default
	}
	return nil
}

func (x *ChecksRequest) GetChecks() []*CheckRequest {
	if x != nil {
		return x.Checks
	}
	return nil
}

// EXPERIMENTAL
type ChecksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Checks        []*CheckResponse       `protobuf:"bytes,1,rep,name=checks,proto3" json:"checks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChecksResponse) Reset() {
	*x = ChecksResponse{}
	mi := &file_aserto_directory_reader_v3_reader_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChecksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChecksResponse) ProtoMessage() {}

func (x *ChecksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_directory_reader_v3_reader_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChecksResponse.ProtoReflect.Descriptor instead.
func (*ChecksResponse) Descriptor() ([]byte, []int) {
	return file_aserto_directory_reader_v3_reader_proto_rawDescGZIP(), []int{13}
}

func (x *ChecksResponse) GetChecks() []*CheckResponse {
	if x != nil {
		return x.Checks
	}
	return nil
}

type CheckPermissionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// object type
	ObjectType string `protobuf:"bytes,1,opt,name=object_type,json=objectType,proto3" json:"object_type,omitempty"`
	// object identifier
	ObjectId string `protobuf:"bytes,2,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	// permission name
	Permission string `protobuf:"bytes,3,opt,name=permission,proto3" json:"permission,omitempty"`
	// subject type
	SubjectType string `protobuf:"bytes,4,opt,name=subject_type,json=subjectType,proto3" json:"subject_type,omitempty"`
	// subject identifier
	SubjectId string `protobuf:"bytes,5,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	// collect trace information
	Trace         bool `protobuf:"varint,7,opt,name=trace,proto3" json:"trace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPermissionRequest) Reset() {
	*x = CheckPermissionRequest{}
	mi := &file_aserto_directory_reader_v3_reader_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPermissionRequest) ProtoMessage() {}

func (x *CheckPermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_directory_reader_v3_reader_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPermissionRequest.ProtoReflect.Descriptor instead.
func (*CheckPermissionRequest) Descriptor() ([]byte, []int) {
	return file_aserto_directory_reader_v3_reader_proto_rawDescGZIP(), []int{14}
}

func (x *CheckPermissionRequest) GetObjectType() string {
	if x != nil {
		return x.ObjectType
	}
	return ""
}

func (x *CheckPermissionRequest) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *CheckPermissionRequest) GetPermission() string {
	if x != nil {
		return x.Permission
	}
	return ""
}

func (x *CheckPermissionRequest) GetSubjectType() string {
	if x != nil {
		return x.SubjectType
	}
	return ""
}

func (x *CheckPermissionRequest) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *CheckPermissionRequest) GetTrace() bool {
	if x != nil {
		return x.Trace
	}
	return false
}

type CheckPermissionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// check result
	Check bool `protobuf:"varint,1,opt,name=check,proto3" json:"check,omitempty"`
	// trace information
	Trace         []string `protobuf:"bytes,2,rep,name=trace,proto3" json:"trace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPermissionResponse) Reset() {
	*x = CheckPermissionResponse{}
	mi := &file_aserto_directory_reader_v3_reader_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPermissionResponse) ProtoMessage() {}

func (x *CheckPermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_directory_reader_v3_reader_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPermissionResponse.ProtoReflect.Descriptor instead.
func (*CheckPermissionResponse) Descriptor() ([]byte, []int) {
	return file_aserto_directory_reader_v3_reader_proto_rawDescGZIP(), []int{15}
}

func (x *CheckPermissionResponse) GetCheck() bool {
	if x != nil {
		return x.Check
	}
	return false
}

func (x *CheckPermissionResponse) GetTrace() []string {
	if x != nil {
		return x.Trace
	}
	return nil
}

type CheckRelationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// object type
	ObjectType string `protobuf:"bytes,1,opt,name=object_type,json=objectType,proto3" json:"object_type,omitempty"`
	// object identifier
	ObjectId string `protobuf:"bytes,2,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	// relation name
	Relation string `protobuf:"bytes,3,opt,name=relation,proto3" json:"relation,omitempty"`
	// subject type
	SubjectType string `protobuf:"bytes,4,opt,name=subject_type,json=subjectType,proto3" json:"subject_type,omitempty"`
	// subject identifier
	SubjectId string `protobuf:"bytes,5,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	// collect trace information
	Trace         bool `protobuf:"varint,7,opt,name=trace,proto3" json:"trace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRelationRequest) Reset() {
	*x = CheckRelationRequest{}
	mi := &file_aserto_directory_reader_v3_reader_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRelationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRelationRequest) ProtoMessage() {}

func (x *CheckRelationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_directory_reader_v3_reader_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRelationRequest.ProtoReflect.Descriptor instead.
func (*CheckRelationRequest) Descriptor() ([]byte, []int) {
	return file_aserto_directory_reader_v3_reader_proto_rawDescGZIP(), []int{16}
}

func (x *CheckRelationRequest) GetObjectType() string {
	if x != nil {
		return x.ObjectType
	}
	return ""
}

func (x *CheckRelationRequest) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *CheckRelationRequest) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

func (x *CheckRelationRequest) GetSubjectType() string {
	if x != nil {
		return x.SubjectType
	}
	return ""
}

func (x *CheckRelationRequest) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *CheckRelationRequest) GetTrace() bool {
	if x != nil {
		return x.Trace
	}
	return false
}

type CheckRelationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// check result
	Check bool `protobuf:"varint,1,opt,name=check,proto3" json:"check,omitempty"`
	// trace information
	Trace         []string `protobuf:"bytes,2,rep,name=trace,proto3" json:"trace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRelationResponse) Reset() {
	*x = CheckRelationResponse{}
	mi := &file_aserto_directory_reader_v3_reader_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRelationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRelationResponse) ProtoMessage() {}

func (x *CheckRelationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_directory_reader_v3_reader_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRelationResponse.ProtoReflect.Descriptor instead.
func (*CheckRelationResponse) Descriptor() ([]byte, []int) {
	return file_aserto_directory_reader_v3_reader_proto_rawDescGZIP(), []int{17}
}

func (x *CheckRelationResponse) GetCheck() bool {
	if x != nil {
		return x.Check
	}
	return false
}

func (x *CheckRelationResponse) GetTrace() []string {
	if x != nil {
		return x.Trace
	}
	return nil
}

type GetGraphRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// object type
	ObjectType string `protobuf:"bytes,3,opt,name=object_type,json=objectType,proto3" json:"object_type,omitempty"`
	// object identifier
	ObjectId string `protobuf:"bytes,4,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	// relation name
	Relation string `protobuf:"bytes,5,opt,name=relation,proto3" json:"relation,omitempty"`
	// subject type
	SubjectType string `protobuf:"bytes,6,opt,name=subject_type,json=subjectType,proto3" json:"subject_type,omitempty"`
	// subject identifier
	SubjectId string `protobuf:"bytes,7,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	// subject relation
	SubjectRelation string `protobuf:"bytes,8,opt,name=subject_relation,json=subjectRelation,proto3" json:"subject_relation,omitempty"`
	// return graph paths for each result
	Explain bool `protobuf:"varint,9,opt,name=explain,proto3" json:"explain,omitempty"`
	// collect trace information
	Trace         bool `protobuf:"varint,10,opt,name=trace,proto3" json:"trace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGraphRequest) Reset() {
	*x = GetGraphRequest{}
	mi := &file_aserto_directory_reader_v3_reader_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGraphRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGraphRequest) ProtoMessage() {}

func (x *GetGraphRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_directory_reader_v3_reader_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGraphRequest.ProtoReflect.Descriptor instead.
func (*GetGraphRequest) Descriptor() ([]byte, []int) {
	return file_aserto_directory_reader_v3_reader_proto_rawDescGZIP(), []int{18}
}

func (x *GetGraphRequest) GetObjectType() string {
	if x != nil {
		return x.ObjectType
	}
	return ""
}

func (x *GetGraphRequest) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *GetGraphRequest) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

func (x *GetGraphRequest) GetSubjectType() string {
	if x != nil {
		return x.SubjectType
	}
	return ""
}

func (x *GetGraphRequest) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *GetGraphRequest) GetSubjectRelation() string {
	if x != nil {
		return x.SubjectRelation
	}
	return ""
}

func (x *GetGraphRequest) GetExplain() bool {
	if x != nil {
		return x.Explain
	}
	return false
}

func (x *GetGraphRequest) GetTrace() bool {
	if x != nil {
		return x.Trace
	}
	return false
}

type GetGraphResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// matching object identifiers
	Results []*v3.ObjectIdentifier `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	// explanation of results
	Explanation *structpb.Struct `protobuf:"bytes,3,opt,name=explanation,proto3" json:"explanation,omitempty"`
	// trace information
	Trace         []string `protobuf:"bytes,4,rep,name=trace,proto3" json:"trace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGraphResponse) Reset() {
	*x = GetGraphResponse{}
	mi := &file_aserto_directory_reader_v3_reader_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGraphResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGraphResponse) ProtoMessage() {}

func (x *GetGraphResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_directory_reader_v3_reader_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGraphResponse.ProtoReflect.Descriptor instead.
func (*GetGraphResponse) Descriptor() ([]byte, []int) {
	return file_aserto_directory_reader_v3_reader_proto_rawDescGZIP(), []int{19}
}

func (x *GetGraphResponse) GetResults() []*v3.ObjectIdentifier {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *GetGraphResponse) GetExplanation() *structpb.Struct {
	if x != nil {
		return x.Explanation
	}
	return nil
}

func (x *GetGraphResponse) GetTrace() []string {
	if x != nil {
		return x.Trace
	}
	return nil
}

var File_aserto_directory_reader_v3_reader_proto protoreflect.FileDescriptor

const file_aserto_directory_reader_v3_reader_proto_rawDesc = "" +
	"\n" +
	"'aserto/directory/reader/v3/reader.proto\x12\x1aaserto.directory.reader.v3\x1a'aserto/directory/common/v3/common.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xce\x01\n" +
	"\x10GetObjectRequest\x12$\n" +
	"\vobject_type\x18\x01 \x01(\tB\x03\xe0A\x02R\n" +
	"objectType\x12 \n" +
	"\tobject_id\x18\x02 \x01(\tB\x03\xe0A\x02R\bobjectId\x12*\n" +
	"\x0ewith_relations\x18\x03 \x01(\bB\x03\xe0A\x01R\rwithRelations\x12F\n" +
	"\x04page\x18\t \x01(\v2-.aserto.directory.common.v3.PaginationRequestB\x03\xe0A\x01R\x04page\"\xd7\x01\n" +
	"\x11GetObjectResponse\x12:\n" +
	"\x06result\x18\x01 \x01(\v2\".aserto.directory.common.v3.ObjectR\x06result\x12B\n" +
	"\trelations\x18\x04 \x03(\v2$.aserto.directory.common.v3.RelationR\trelations\x12B\n" +
	"\x04page\x18\t \x01(\v2..aserto.directory.common.v3.PaginationResponseR\x04page\"_\n" +
	"\x14GetObjectManyRequest\x12G\n" +
	"\x05param\x18\x01 \x03(\v2,.aserto.directory.common.v3.ObjectIdentifierB\x03\xe0A\x02R\x05param\"U\n" +
	"\x15GetObjectManyResponse\x12<\n" +
	"\aresults\x18\x01 \x03(\v2\".aserto.directory.common.v3.ObjectR\aresults\"\x81\x01\n" +
	"\x11GetObjectsRequest\x12$\n" +
	"\vobject_type\x18\x01 \x01(\tB\x03\xe0A\x01R\n" +
	"objectType\x12F\n" +
	"\x04page\x18\t \x01(\v2-.aserto.directory.common.v3.PaginationRequestB\x03\xe0A\x01R\x04page\"\x96\x01\n" +
	"\x12GetObjectsResponse\x12<\n" +
	"\aresults\x18\x01 \x03(\v2\".aserto.directory.common.v3.ObjectR\aresults\x12B\n" +
	"\x04page\x18\t \x01(\v2..aserto.directory.common.v3.PaginationResponseR\x04page\"\xa1\x02\n" +
	"\x12GetRelationRequest\x12$\n" +
	"\vobject_type\x18\x01 \x01(\tB\x03\xe0A\x02R\n" +
	"objectType\x12 \n" +
	"\tobject_id\x18\x02 \x01(\tB\x03\xe0A\x02R\bobjectId\x12\x1f\n" +
	"\brelation\x18\x03 \x01(\tB\x03\xe0A\x02R\brelation\x12&\n" +
	"\fsubject_type\x18\x04 \x01(\tB\x03\xe0A\x02R\vsubjectType\x12\"\n" +
	"\n" +
	"subject_id\x18\x05 \x01(\tB\x03\xe0A\x02R\tsubjectId\x12.\n" +
	"\x10subject_relation\x18\x06 \x01(\tB\x03\xe0A\x01R\x0fsubjectRelation\x12&\n" +
	"\fwith_objects\x18\a \x01(\bB\x03\xe0A\x01R\vwithObjects\"\x8b\x02\n" +
	"\x13GetRelationResponse\x12<\n" +
	"\x06result\x18\x01 \x01(\v2$.aserto.directory.common.v3.RelationR\x06result\x12V\n" +
	"\aobjects\x18\x02 \x03(\v2<.aserto.directory.reader.v3.GetRelationResponse.ObjectsEntryR\aobjects\x1a^\n" +
	"\fObjectsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x128\n" +
	"\x05value\x18\x02 \x01(\v2\".aserto.directory.common.v3.ObjectR\x05value:\x028\x01\"\xae\x03\n" +
	"\x13GetRelationsRequest\x12$\n" +
	"\vobject_type\x18\x01 \x01(\tB\x03\xe0A\x01R\n" +
	"objectType\x12 \n" +
	"\tobject_id\x18\x02 \x01(\tB\x03\xe0A\x01R\bobjectId\x12\x1f\n" +
	"\brelation\x18\x03 \x01(\tB\x03\xe0A\x01R\brelation\x12&\n" +
	"\fsubject_type\x18\x04 \x01(\tB\x03\xe0A\x01R\vsubjectType\x12\"\n" +
	"\n" +
	"subject_id\x18\x05 \x01(\tB\x03\xe0A\x01R\tsubjectId\x12.\n" +
	"\x10subject_relation\x18\x06 \x01(\tB\x03\xe0A\x01R\x0fsubjectRelation\x12&\n" +
	"\fwith_objects\x18\a \x01(\bB\x03\xe0A\x01R\vwithObjects\x12B\n" +
	"\x1bwith_empty_subject_relation\x18\b \x01(\bB\x03\xe0A\x01R\x18withEmptySubjectRelation\x12F\n" +
	"\x04page\x18\t \x01(\v2-.aserto.directory.common.v3.PaginationRequestB\x03\xe0A\x01R\x04page\"\xd3\x02\n" +
	"\x14GetRelationsResponse\x12>\n" +
	"\aresults\x18\x01 \x03(\v2$.aserto.directory.common.v3.RelationR\aresults\x12W\n" +
	"\aobjects\x18\x02 \x03(\v2=.aserto.directory.reader.v3.GetRelationsResponse.ObjectsEntryR\aobjects\x12B\n" +
	"\x04page\x18\t \x01(\v2..aserto.directory.common.v3.PaginationResponseR\x04page\x1a^\n" +
	"\fObjectsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x128\n" +
	"\x05value\x18\x02 \x01(\v2\".aserto.directory.common.v3.ObjectR\x05value:\x028\x01\"\xde\x01\n" +
	"\fCheckRequest\x12$\n" +
	"\vobject_type\x18\x01 \x01(\tB\x03\xe0A\x02R\n" +
	"objectType\x12 \n" +
	"\tobject_id\x18\x02 \x01(\tB\x03\xe0A\x02R\bobjectId\x12\x1f\n" +
	"\brelation\x18\x03 \x01(\tB\x03\xe0A\x02R\brelation\x12&\n" +
	"\fsubject_type\x18\x04 \x01(\tB\x03\xe0A\x02R\vsubjectType\x12\"\n" +
	"\n" +
	"subject_id\x18\x05 \x01(\tB\x03\xe0A\x02R\tsubjectId\x12\x19\n" +
	"\x05trace\x18\a \x01(\bB\x03\xe0A\x01R\x05trace\"n\n" +
	"\rCheckResponse\x12\x14\n" +
	"\x05check\x18\x01 \x01(\bR\x05check\x12\x14\n" +
	"\x05trace\x18\x02 \x03(\tR\x05trace\x121\n" +
	"\acontext\x18\x03 \x01(\v2\x17.google.protobuf.StructR\acontext\"\x95\x01\n" +
	"\rChecksRequest\x12B\n" +
	"\adefault\x18\x01 \x01(\v2(.aserto.directory.reader.v3.CheckRequestR\adefault\x12@\n" +
	"\x06checks\x18\x02 \x03(\v2(.aserto.directory.reader.v3.CheckRequestR\x06checks\"S\n" +
	"\x0eChecksResponse\x12A\n" +
	"\x06checks\x18\x01 \x03(\v2).aserto.directory.reader.v3.CheckResponseR\x06checks\"\xec\x01\n" +
	"\x16CheckPermissionRequest\x12$\n" +
	"\vobject_type\x18\x01 \x01(\tB\x03\xe0A\x02R\n" +
	"objectType\x12 \n" +
	"\tobject_id\x18\x02 \x01(\tB\x03\xe0A\x02R\bobjectId\x12#\n" +
	"\n" +
	"permission\x18\x03 \x01(\tB\x03\xe0A\x02R\n" +
	"permission\x12&\n" +
	"\fsubject_type\x18\x04 \x01(\tB\x03\xe0A\x02R\vsubjectType\x12\"\n" +
	"\n" +
	"subject_id\x18\x05 \x01(\tB\x03\xe0A\x02R\tsubjectId\x12\x19\n" +
	"\x05trace\x18\a \x01(\bB\x03\xe0A\x01R\x05trace\"E\n" +
	"\x17CheckPermissionResponse\x12\x14\n" +
	"\x05check\x18\x01 \x01(\bR\x05check\x12\x14\n" +
	"\x05trace\x18\x02 \x03(\tR\x05trace\"\xe6\x01\n" +
	"\x14CheckRelationRequest\x12$\n" +
	"\vobject_type\x18\x01 \x01(\tB\x03\xe0A\x02R\n" +
	"objectType\x12 \n" +
	"\tobject_id\x18\x02 \x01(\tB\x03\xe0A\x02R\bobjectId\x12\x1f\n" +
	"\brelation\x18\x03 \x01(\tB\x03\xe0A\x02R\brelation\x12&\n" +
	"\fsubject_type\x18\x04 \x01(\tB\x03\xe0A\x02R\vsubjectType\x12\"\n" +
	"\n" +
	"subject_id\x18\x05 \x01(\tB\x03\xe0A\x02R\tsubjectId\x12\x19\n" +
	"\x05trace\x18\a \x01(\bB\x03\xe0A\x01R\x05trace\"C\n" +
	"\x15CheckRelationResponse\x12\x14\n" +
	"\x05check\x18\x01 \x01(\bR\x05check\x12\x14\n" +
	"\x05trace\x18\x02 \x03(\tR\x05trace\"\xd4\x02\n" +
	"\x0fGetGraphRequest\x12$\n" +
	"\vobject_type\x18\x03 \x01(\tB\x03\xe0A\x02R\n" +
	"objectType\x12 \n" +
	"\tobject_id\x18\x04 \x01(\tB\x03\xe0A\x01R\bobjectId\x12\x1f\n" +
	"\brelation\x18\x05 \x01(\tB\x03\xe0A\x02R\brelation\x12&\n" +
	"\fsubject_type\x18\x06 \x01(\tB\x03\xe0A\x02R\vsubjectType\x12\"\n" +
	"\n" +
	"subject_id\x18\a \x01(\tB\x03\xe0A\x01R\tsubjectId\x12.\n" +
	"\x10subject_relation\x18\b \x01(\tB\x03\xe0A\x01R\x0fsubjectRelation\x12\x1d\n" +
	"\aexplain\x18\t \x01(\bB\x03\xe0A\x01R\aexplain\x12\x19\n" +
	"\x05trace\x18\n" +
	" \x01(\bB\x03\xe0A\x01R\x05traceJ\x04\b\x01\x10\x02J\x04\b\x02\x10\x03R\vanchor_typeR\tanchor_id\"\xb1\x01\n" +
	"\x10GetGraphResponse\x12F\n" +
	"\aresults\x18\x02 \x03(\v2,.aserto.directory.common.v3.ObjectIdentifierR\aresults\x129\n" +
	"\vexplanation\x18\x03 \x01(\v2\x17.google.protobuf.StructR\vexplanation\x12\x14\n" +
	"\x05trace\x18\x04 \x03(\tR\x05traceJ\x04\b\x01\x10\x022\xc5\x16\n" +
	"\x06Reader\x12\xe9\x02\n" +
	"\tGetObject\x12,.aserto.directory.reader.v3.GetObjectRequest\x1a-.aserto.directory.reader.v3.GetObjectResponse\"\xfe\x01\x92A\xc0\x01\n" +
	"\tdirectory\x12\x13Get object instance\x1a:Returns single object instance, optionally with relations.*\x1edirectory.reader.v3.object.getJ\x1d\n" +
	"\x03304\x12\x16\n" +
	"\x14Object not modified.b#\n" +
	"\x13\n" +
	"\x0fDirectoryAPIKey\x12\x00\n" +
	"\f\n" +
	"\bTenantID\x12\x00\x82\xd3\xe4\x93\x024\x122/api/v3/directory/object/{object_type}/{object_id}\x12v\n" +
	"\rGetObjectMany\x120.aserto.directory.reader.v3.GetObjectManyRequest\x1a1.aserto.directory.reader.v3.GetObjectManyResponse\"\x00\x12\x9f\x02\n" +
	"\n" +
	"GetObjects\x12-.aserto.directory.reader.v3.GetObjectsRequest\x1a..aserto.directory.reader.v3.GetObjectsResponse\"\xb1\x01\x92A\x8c\x01\n" +
	"\tdirectory\x12\x15List object instances\x1a!Returns list of object instances.* directory.reader.v3.objects.listb#\n" +
	"\x13\n" +
	"\x0fDirectoryAPIKey\x12\x00\n" +
	"\f\n" +
	"\bTenantID\x12\x00\x82\xd3\xe4\x93\x02\x1b\x12\x19/api/v3/directory/objects\x12\xdd\x02\n" +
	"\vGetRelation\x12..aserto.directory.reader.v3.GetRelationRequest\x1a/.aserto.directory.reader.v3.GetRelationResponse\"\xec\x01\x92A\xc6\x01\n" +
	"\tdirectory\x12\x15Get relation instance\x1a:Returns single relation instance, optionally with objects.* directory.reader.v3.relation.getJ\x1f\n" +
	"\x03304\x12\x18\n" +
	"\x16Relation not modified.b#\n" +
	"\x13\n" +
	"\x0fDirectoryAPIKey\x12\x00\n" +
	"\f\n" +
	"\bTenantID\x12\x00\x82\xd3\xe4\x93\x02\x1c\x12\x1a/api/v3/directory/relation\x12\xae\x02\n" +
	"\fGetRelations\x12/.aserto.directory.reader.v3.GetRelationsRequest\x1a0.aserto.directory.reader.v3.GetRelationsResponse\"\xba\x01\x92A\x93\x01\n" +
	"\tdirectory\x12\x18List relations instances\x1a#Returns list of relation instances.*\"directory.reader.v3.relations.listb#\n" +
	"\x13\n" +
	"\x0fDirectoryAPIKey\x12\x00\n" +
	"\f\n" +
	"\bTenantID\x12\x00\x82\xd3\xe4\x93\x02\x1d\x12\x1b/api/v3/directory/relations\x12\xee\x01\n" +
	"\x05Check\x12(.aserto.directory.reader.v3.CheckRequest\x1a).aserto.directory.reader.v3.CheckResponse\"\x8f\x01\x92Aj\n" +
	"\tdirectory\x12\x05Check\x1a\x16Returns check outcome.*\x19directory.reader.v3.checkb#\n" +
	"\x13\n" +
	"\x0fDirectoryAPIKey\x12\x00\n" +
	"\f\n" +
	"\bTenantID\x12\x00\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/api/v3/directory/check\x12\xfe\x01\n" +
	"\x06Checks\x12).aserto.directory.reader.v3.ChecksRequest\x1a*.aserto.directory.reader.v3.ChecksResponse\"\x9c\x01\x92Av\n" +
	"\tdirectory\x12\x06Checks\x1a Returns multiple check outcomes.*\x1adirectory.reader.v3.checksb#\n" +
	"\x13\n" +
	"\x0fDirectoryAPIKey\x12\x00\n" +
	"\f\n" +
	"\bTenantID\x12\x00\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/api/v3/directory/checks\x12\xbc\x02\n" +
	"\x0fCheckPermission\x122.aserto.directory.reader.v3.CheckPermissionRequest\x1a3.aserto.directory.reader.v3.CheckPermissionResponse\"\xbf\x01\x92A\x8b\x01\n" +
	"\tdirectory\x12\x10Check permission\x1a!Returns check permission outcome.*$directory.reader.v3.check.permissionb#\n" +
	"\x13\n" +
	"\x0fDirectoryAPIKey\x12\x00\n" +
	"\f\n" +
	"\bTenantID\x12\x00\x82\xd3\xe4\x93\x02':\x01*\"\"/api/v3/directory/check/permission\x88\x02\x01\x12\xae\x02\n" +
	"\rCheckRelation\x120.aserto.directory.reader.v3.CheckRelationRequest\x1a1.aserto.directory.reader.v3.CheckRelationResponse\"\xb7\x01\x92A\x85\x01\n" +
	"\tdirectory\x12\x0eCheck relation\x1a\x1fReturns check relation outcome.*\"directory.reader.v3.check.relationb#\n" +
	"\x13\n" +
	"\x0fDirectoryAPIKey\x12\x00\n" +
	"\f\n" +
	"\bTenantID\x12\x00\x82\xd3\xe4\x93\x02%:\x01*\" /api/v3/directory/check/relation\x88\x02\x01\x12\xc1\x02\n" +
	"\bGetGraph\x12+.aserto.directory.reader.v3.GetGraphRequest\x1a,.aserto.directory.reader.v3.GetGraphResponse\"\xd9\x01\x92A\x8e\x01\n" +
	"\tdirectory\x12\tGet graph\x1a6Returns object graph from anchor to subject or object.*\x19directory.reader.v3.graphb#\n" +
	"\x13\n" +
	"\x0fDirectoryAPIKey\x12\x00\n" +
	"\f\n" +
	"\bTenantID\x12\x00\x82\xd3\xe4\x93\x02A\x12?/api/v3/directory/graph/{object_type}/{relation}/{subject_type}BFZDgithub.com/aserto-dev/go-directory/aserto/directory/reader/v3;readerb\x06proto3"

var (
	file_aserto_directory_reader_v3_reader_proto_rawDescOnce sync.Once
	file_aserto_directory_reader_v3_reader_proto_rawDescData []byte
)

func file_aserto_directory_reader_v3_reader_proto_rawDescGZIP() []byte {
	file_aserto_directory_reader_v3_reader_proto_rawDescOnce.Do(func() {
		file_aserto_directory_reader_v3_reader_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aserto_directory_reader_v3_reader_proto_rawDesc), len(file_aserto_directory_reader_v3_reader_proto_rawDesc)))
	})
	return file_aserto_directory_reader_v3_reader_proto_rawDescData
}

var file_aserto_directory_reader_v3_reader_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_aserto_directory_reader_v3_reader_proto_goTypes = []any{
	(*GetObjectRequest)(nil),        // 0: aserto.directory.reader.v3.GetObjectRequest
	(*GetObjectResponse)(nil),       // 1: aserto.directory.reader.v3.GetObjectResponse
	(*GetObjectManyRequest)(nil),    // 2: aserto.directory.reader.v3.GetObjectManyRequest
	(*GetObjectManyResponse)(nil),   // 3: aserto.directory.reader.v3.GetObjectManyResponse
	(*GetObjectsRequest)(nil),       // 4: aserto.directory.reader.v3.GetObjectsRequest
	(*GetObjectsResponse)(nil),      // 5: aserto.directory.reader.v3.GetObjectsResponse
	(*GetRelationRequest)(nil),      // 6: aserto.directory.reader.v3.GetRelationRequest
	(*GetRelationResponse)(nil),     // 7: aserto.directory.reader.v3.GetRelationResponse
	(*GetRelationsRequest)(nil),     // 8: aserto.directory.reader.v3.GetRelationsRequest
	(*GetRelationsResponse)(nil),    // 9: aserto.directory.reader.v3.GetRelationsResponse
	(*CheckRequest)(nil),            // 10: aserto.directory.reader.v3.CheckRequest
	(*CheckResponse)(nil),           // 11: aserto.directory.reader.v3.CheckResponse
	(*ChecksRequest)(nil),           // 12: aserto.directory.reader.v3.ChecksRequest
	(*ChecksResponse)(nil),          // 13: aserto.directory.reader.v3.ChecksResponse
	(*CheckPermissionRequest)(nil),  // 14: aserto.directory.reader.v3.CheckPermissionRequest
	(*CheckPermissionResponse)(nil), // 15: aserto.directory.reader.v3.CheckPermissionResponse
	(*CheckRelationRequest)(nil),    // 16: aserto.directory.reader.v3.CheckRelationRequest
	(*CheckRelationResponse)(nil),   // 17: aserto.directory.reader.v3.CheckRelationResponse
	(*GetGraphRequest)(nil),         // 18: aserto.directory.reader.v3.GetGraphRequest
	(*GetGraphResponse)(nil),        // 19: aserto.directory.reader.v3.GetGraphResponse
	nil,                             // 20: aserto.directory.reader.v3.GetRelationResponse.ObjectsEntry
	nil,                             // 21: aserto.directory.reader.v3.GetRelationsResponse.ObjectsEntry
	(*v3.PaginationRequest)(nil),    // 22: aserto.directory.common.v3.PaginationRequest
	(*v3.Object)(nil),               // 23: aserto.directory.common.v3.Object
	(*v3.Relation)(nil),             // 24: aserto.directory.common.v3.Relation
	(*v3.PaginationResponse)(nil),   // 25: aserto.directory.common.v3.PaginationResponse
	(*v3.ObjectIdentifier)(nil),     // 26: aserto.directory.common.v3.ObjectIdentifier
	(*structpb.Struct)(nil),         // 27: google.protobuf.Struct
}
var file_aserto_directory_reader_v3_reader_proto_depIdxs = []int32{
	22, // 0: aserto.directory.reader.v3.GetObjectRequest.page:type_name -> aserto.directory.common.v3.PaginationRequest
	23, // 1: aserto.directory.reader.v3.GetObjectResponse.result:type_name -> aserto.directory.common.v3.Object
	24, // 2: aserto.directory.reader.v3.GetObjectResponse.relations:type_name -> aserto.directory.common.v3.Relation
	25, // 3: aserto.directory.reader.v3.GetObjectResponse.page:type_name -> aserto.directory.common.v3.PaginationResponse
	26, // 4: aserto.directory.reader.v3.GetObjectManyRequest.param:type_name -> aserto.directory.common.v3.ObjectIdentifier
	23, // 5: aserto.directory.reader.v3.GetObjectManyResponse.results:type_name -> aserto.directory.common.v3.Object
	22, // 6: aserto.directory.reader.v3.GetObjectsRequest.page:type_name -> aserto.directory.common.v3.PaginationRequest
	23, // 7: aserto.directory.reader.v3.GetObjectsResponse.results:type_name -> aserto.directory.common.v3.Object
	25, // 8: aserto.directory.reader.v3.GetObjectsResponse.page:type_name -> aserto.directory.common.v3.PaginationResponse
	24, // 9: aserto.directory.reader.v3.GetRelationResponse.result:type_name -> aserto.directory.common.v3.Relation
	20, // 10: aserto.directory.reader.v3.GetRelationResponse.objects:type_name -> aserto.directory.reader.v3.GetRelationResponse.ObjectsEntry
	22, // 11: aserto.directory.reader.v3.GetRelationsRequest.page:type_name -> aserto.directory.common.v3.PaginationRequest
	24, // 12: aserto.directory.reader.v3.GetRelationsResponse.results:type_name -> aserto.directory.common.v3.Relation
	21, // 13: aserto.directory.reader.v3.GetRelationsResponse.objects:type_name -> aserto.directory.reader.v3.GetRelationsResponse.ObjectsEntry
	25, // 14: aserto.directory.reader.v3.GetRelationsResponse.page:type_name -> aserto.directory.common.v3.PaginationResponse
	27, // 15: aserto.directory.reader.v3.CheckResponse.context:type_name -> google.protobuf.Struct
	10, // 16: aserto.directory.reader.v3.ChecksRequest.default:type_name -> aserto.directory.reader.v3.CheckRequest
	10, // 17: aserto.directory.reader.v3.ChecksRequest.checks:type_name -> aserto.directory.reader.v3.CheckRequest
	11, // 18: aserto.directory.reader.v3.ChecksResponse.checks:type_name -> aserto.directory.reader.v3.CheckResponse
	26, // 19: aserto.directory.reader.v3.GetGraphResponse.results:type_name -> aserto.directory.common.v3.ObjectIdentifier
	27, // 20: aserto.directory.reader.v3.GetGraphResponse.explanation:type_name -> google.protobuf.Struct
	23, // 21: aserto.directory.reader.v3.GetRelationResponse.ObjectsEntry.value:type_name -> aserto.directory.common.v3.Object
	23, // 22: aserto.directory.reader.v3.GetRelationsResponse.ObjectsEntry.value:type_name -> aserto.directory.common.v3.Object
	0,  // 23: aserto.directory.reader.v3.Reader.GetObject:input_type -> aserto.directory.reader.v3.GetObjectRequest
	2,  // 24: aserto.directory.reader.v3.Reader.GetObjectMany:input_type -> aserto.directory.reader.v3.GetObjectManyRequest
	4,  // 25: aserto.directory.reader.v3.Reader.GetObjects:input_type -> aserto.directory.reader.v3.GetObjectsRequest
	6,  // 26: aserto.directory.reader.v3.Reader.GetRelation:input_type -> aserto.directory.reader.v3.GetRelationRequest
	8,  // 27: aserto.directory.reader.v3.Reader.GetRelations:input_type -> aserto.directory.reader.v3.GetRelationsRequest
	10, // 28: aserto.directory.reader.v3.Reader.Check:input_type -> aserto.directory.reader.v3.CheckRequest
	12, // 29: aserto.directory.reader.v3.Reader.Checks:input_type -> aserto.directory.reader.v3.ChecksRequest
	14, // 30: aserto.directory.reader.v3.Reader.CheckPermission:input_type -> aserto.directory.reader.v3.CheckPermissionRequest
	16, // 31: aserto.directory.reader.v3.Reader.CheckRelation:input_type -> aserto.directory.reader.v3.CheckRelationRequest
	18, // 32: aserto.directory.reader.v3.Reader.GetGraph:input_type -> aserto.directory.reader.v3.GetGraphRequest
	1,  // 33: aserto.directory.reader.v3.Reader.GetObject:output_type -> aserto.directory.reader.v3.GetObjectResponse
	3,  // 34: aserto.directory.reader.v3.Reader.GetObjectMany:output_type -> aserto.directory.reader.v3.GetObjectManyResponse
	5,  // 35: aserto.directory.reader.v3.Reader.GetObjects:output_type -> aserto.directory.reader.v3.GetObjectsResponse
	7,  // 36: aserto.directory.reader.v3.Reader.GetRelation:output_type -> aserto.directory.reader.v3.GetRelationResponse
	9,  // 37: aserto.directory.reader.v3.Reader.GetRelations:output_type -> aserto.directory.reader.v3.GetRelationsResponse
	11, // 38: aserto.directory.reader.v3.Reader.Check:output_type -> aserto.directory.reader.v3.CheckResponse
	13, // 39: aserto.directory.reader.v3.Reader.Checks:output_type -> aserto.directory.reader.v3.ChecksResponse
	15, // 40: aserto.directory.reader.v3.Reader.CheckPermission:output_type -> aserto.directory.reader.v3.CheckPermissionResponse
	17, // 41: aserto.directory.reader.v3.Reader.CheckRelation:output_type -> aserto.directory.reader.v3.CheckRelationResponse
	19, // 42: aserto.directory.reader.v3.Reader.GetGraph:output_type -> aserto.directory.reader.v3.GetGraphResponse
	33, // [33:43] is the sub-list for method output_type
	23, // [23:33] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_aserto_directory_reader_v3_reader_proto_init() }
func file_aserto_directory_reader_v3_reader_proto_init() {
	if File_aserto_directory_reader_v3_reader_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aserto_directory_reader_v3_reader_proto_rawDesc), len(file_aserto_directory_reader_v3_reader_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_aserto_directory_reader_v3_reader_proto_goTypes,
		DependencyIndexes: file_aserto_directory_reader_v3_reader_proto_depIdxs,
		MessageInfos:      file_aserto_directory_reader_v3_reader_proto_msgTypes,
	}.Build()
	File_aserto_directory_reader_v3_reader_proto = out.File
	file_aserto_directory_reader_v3_reader_proto_goTypes = nil
	file_aserto_directory_reader_v3_reader_proto_depIdxs = nil
}
