syntax = "proto3";

package aserto.directory.common.v3;

import "google/api/field_behavior.proto";
import "google/protobuf/struct.proto";
import "google/protobuf/timestamp.proto";

option go_package = "github.com/aserto-dev/go-directory/aserto/directory/common/v3;common";

// Manifest
message Manifest {
  reserved 1;
  reserved "manifest_id";

  // manifest data stream
  bytes content = 2 [
    json_name = "content",
    (google.api.field_behavior) = REQUIRED,
    deprecated = false
  ];
  // last updated timestamp (UTC)
  google.protobuf.Timestamp updated_at = 21 [
    json_name = "updated_at",
    (google.api.field_behavior) = OUTPUT_ONLY,
    deprecated = false
  ];
  // object instance etag
  string etag = 23 [
    json_name = "etag",
    (google.api.field_behavior) = OUTPUT_ONLY,
    deprecated = false
  ];
}

// Model
message Model {
  reserved 1;
  reserved "model_id";

  // model data stream
  google.protobuf.Struct content = 2 [
    json_name = "content",
    (google.api.field_behavior) = REQUIRED,
    deprecated = false
  ];
  // last updated timestamp (UTC)
  google.protobuf.Timestamp updated_at = 21 [
    json_name = "updated_at",
    (google.api.field_behavior) = OUTPUT_ONLY,
    deprecated = false
  ];
  // object instance etag
  string etag = 23 [
    json_name = "etag",
    (google.api.field_behavior) = OUTPUT_ONLY,
    deprecated = false
  ];
}

// Object
message Object {
  // object type identifier
  string type = 1 [
    json_name = "type",
    (google.api.field_behavior) = REQUIRED,
    deprecated = true
  ];
  // object instance identifier
  string id = 2 [
    json_name = "id",
    (google.api.field_behavior) = REQUIRED,
    deprecated = true
  ];
  // display name object (optional) (DEPRECATED)
  string display_name = 3 [
    json_name = "display_name",
    (google.api.field_behavior) = OPTIONAL,
    deprecated = true
  ];
  // object type identifier
  string object_type = 11 [
    json_name = "object_type",
    (google.api.field_behavior) = REQUIRED,
    deprecated = false
  ];
  // object instance identifier
  string object_id = 12 [
    json_name = "object_id",
    (google.api.field_behavior) = REQUIRED,
    deprecated = false
  ];
  // property bag (optional)
  google.protobuf.Struct properties = 4 [
    json_name = "properties",
    (google.api.field_behavior) = OPTIONAL,
    deprecated = false
  ];
  // created at timestamp (UTC) (DEPRECATED)
  google.protobuf.Timestamp created_at = 20 [
    json_name = "created_at",
    (google.api.field_behavior) = OUTPUT_ONLY,
    deprecated = true
  ];
  // last updated timestamp (UTC)
  google.protobuf.Timestamp updated_at = 21 [
    json_name = "updated_at",
    (google.api.field_behavior) = OUTPUT_ONLY,
    deprecated = false
  ];
  // object instance etag
  string etag = 23 [
    json_name = "etag",
    (google.api.field_behavior) = OUTPUT_ONLY,
    deprecated = false
  ];
}

// Relation
message Relation {
  // object type identifier
  string object_type = 1 [
    json_name = "object_type",
    (google.api.field_behavior) = REQUIRED,
    deprecated = false
  ];
  // object instance identifier
  string object_id = 2 [
    json_name = "object_id",
    (google.api.field_behavior) = REQUIRED,
    deprecated = false
  ];
  // object relation name
  string relation = 3 [
    json_name = "relation",
    (google.api.field_behavior) = REQUIRED,
    deprecated = false
  ];
  // subject type identifier
  string subject_type = 4 [
    json_name = "subject_type",
    (google.api.field_behavior) = REQUIRED,
    deprecated = false
  ];
  // subject instance identifier
  string subject_id = 5 [
    json_name = "subject_id",
    (google.api.field_behavior) = REQUIRED,
    deprecated = false
  ];
  // subject relation name (optional)
  string subject_relation = 6 [
    json_name = "subject_relation",
    (google.api.field_behavior) = OPTIONAL,
    deprecated = false
  ];
  // created at timestamp (UTC) (DEPRECATED)
  google.protobuf.Timestamp created_at = 20 [
    json_name = "created_at",
    (google.api.field_behavior) = OUTPUT_ONLY,
    deprecated = true
  ];
  // last updated timestamp (UTC)
  google.protobuf.Timestamp updated_at = 21 [
    json_name = "updated_at",
    (google.api.field_behavior) = OUTPUT_ONLY,
    deprecated = false
  ];
  // relation instance etag
  string etag = 23 [
    json_name = "etag",
    (google.api.field_behavior) = OUTPUT_ONLY,
    deprecated = false
  ];
}

// Object identifier
message ObjectIdentifier {
  // object type identifier
  string object_type = 1 [
    json_name = "object_type",
    (google.api.field_behavior) = REQUIRED,
    deprecated = false
  ];
  // object instance identifier
  string object_id = 2 [
    json_name = "object_id",
    (google.api.field_behavior) = REQUIRED,
    deprecated = false
  ];
}

// Relation identifier
message RelationIdentifier {
  // object type identifier
  string object_type = 1 [
    json_name = "object_type",
    (google.api.field_behavior) = REQUIRED,
    deprecated = false
  ];
  // object instance identifier
  string object_id = 2 [
    json_name = "object_id",
    (google.api.field_behavior) = REQUIRED,
    deprecated = false
  ];
  // object relation name
  string relation = 3 [
    json_name = "relation",
    (google.api.field_behavior) = REQUIRED,
    deprecated = false
  ];
  // subject type identifier
  string subject_type = 4 [
    json_name = "subject_type",
    (google.api.field_behavior) = REQUIRED,
    deprecated = false
  ];
  // subject instance identifier
  string subject_id = 5 [
    json_name = "subject_id",
    (google.api.field_behavior) = REQUIRED,
    deprecated = false
  ];
  //subject relation name (optional)
  string subject_relation = 6 [
    json_name = "subject_relation",
    (google.api.field_behavior) = OPTIONAL,
    deprecated = false
  ];
}

// Pagination request
message PaginationRequest {
  // requested page size, valid value between 1-100 rows (optional, default 100)
  int32 size = 1 [
    json_name = "size",
    (google.api.field_behavior) = OPTIONAL,
    deprecated = false
  ];
  // pagination start token (optional, default "")
  string token = 2 [
    json_name = "token",
    (google.api.field_behavior) = OPTIONAL,
    deprecated = false
  ];
}

// Pagination response
message PaginationResponse {
  // next page token, when empty there are no more pages to fetch
  string next_token = 1 [
    json_name = "next_token",
    (google.api.field_behavior) = OUTPUT_ONLY,
    deprecated = false
  ];
}
