// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: aserto/directory/writer/v3/writer.proto

package writer

import (
	v3 "github.com/aserto-dev/go-directory/aserto/directory/common/v3"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Opcode int32

const (
	Opcode_OPCODE_UNKNOWN               Opcode = 0
	Opcode_OPCODE_SET                   Opcode = 1
	Opcode_OPCODE_DELETE                Opcode = 2
	Opcode_OPCODE_DELETE_WITH_RELATIONS Opcode = 3
)

// Enum value maps for Opcode.
var (
	Opcode_name = map[int32]string{
		0: "OPCODE_UNKNOWN",
		1: "OPCODE_SET",
		2: "OPCODE_DELETE",
		3: "OPCODE_DELETE_WITH_RELATIONS",
	}
	Opcode_value = map[string]int32{
		"OPCODE_UNKNOWN":               0,
		"OPCODE_SET":                   1,
		"OPCODE_DELETE":                2,
		"OPCODE_DELETE_WITH_RELATIONS": 3,
	}
)

func (x Opcode) Enum() *Opcode {
	p := new(Opcode)
	*p = x
	return p
}

func (x Opcode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Opcode) Descriptor() protoreflect.EnumDescriptor {
	return file_aserto_directory_writer_v3_writer_proto_enumTypes[0].Descriptor()
}

func (Opcode) Type() protoreflect.EnumType {
	return &file_aserto_directory_writer_v3_writer_proto_enumTypes[0]
}

func (x Opcode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Opcode.Descriptor instead.
func (Opcode) EnumDescriptor() ([]byte, []int) {
	return file_aserto_directory_writer_v3_writer_proto_rawDescGZIP(), []int{0}
}

type SetObjectRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// object instance
	Object        *v3.Object `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetObjectRequest) Reset() {
	*x = SetObjectRequest{}
	mi := &file_aserto_directory_writer_v3_writer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetObjectRequest) ProtoMessage() {}

func (x *SetObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_directory_writer_v3_writer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetObjectRequest.ProtoReflect.Descriptor instead.
func (*SetObjectRequest) Descriptor() ([]byte, []int) {
	return file_aserto_directory_writer_v3_writer_proto_rawDescGZIP(), []int{0}
}

func (x *SetObjectRequest) GetObject() *v3.Object {
	if x != nil {
		return x.Object
	}
	return nil
}

type SetObjectResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// object instance
	Result        *v3.Object `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetObjectResponse) Reset() {
	*x = SetObjectResponse{}
	mi := &file_aserto_directory_writer_v3_writer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetObjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetObjectResponse) ProtoMessage() {}

func (x *SetObjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_directory_writer_v3_writer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetObjectResponse.ProtoReflect.Descriptor instead.
func (*SetObjectResponse) Descriptor() ([]byte, []int) {
	return file_aserto_directory_writer_v3_writer_proto_rawDescGZIP(), []int{1}
}

func (x *SetObjectResponse) GetResult() *v3.Object {
	if x != nil {
		return x.Result
	}
	return nil
}

type DeleteObjectRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// object type
	ObjectType string `protobuf:"bytes,1,opt,name=object_type,json=objectType,proto3" json:"object_type,omitempty"`
	// object identifier
	ObjectId string `protobuf:"bytes,2,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	// delete object relations, both object and subject relations.
	WithRelations bool `protobuf:"varint,3,opt,name=with_relations,json=withRelations,proto3" json:"with_relations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteObjectRequest) Reset() {
	*x = DeleteObjectRequest{}
	mi := &file_aserto_directory_writer_v3_writer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteObjectRequest) ProtoMessage() {}

func (x *DeleteObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_directory_writer_v3_writer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteObjectRequest.ProtoReflect.Descriptor instead.
func (*DeleteObjectRequest) Descriptor() ([]byte, []int) {
	return file_aserto_directory_writer_v3_writer_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteObjectRequest) GetObjectType() string {
	if x != nil {
		return x.ObjectType
	}
	return ""
}

func (x *DeleteObjectRequest) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *DeleteObjectRequest) GetWithRelations() bool {
	if x != nil {
		return x.WithRelations
	}
	return false
}

type DeleteObjectResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// empty result
	Result        *emptypb.Empty `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteObjectResponse) Reset() {
	*x = DeleteObjectResponse{}
	mi := &file_aserto_directory_writer_v3_writer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteObjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteObjectResponse) ProtoMessage() {}

func (x *DeleteObjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_directory_writer_v3_writer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteObjectResponse.ProtoReflect.Descriptor instead.
func (*DeleteObjectResponse) Descriptor() ([]byte, []int) {
	return file_aserto_directory_writer_v3_writer_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteObjectResponse) GetResult() *emptypb.Empty {
	if x != nil {
		return x.Result
	}
	return nil
}

type SetRelationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// relation instance
	Relation      *v3.Relation `protobuf:"bytes,1,opt,name=relation,proto3" json:"relation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRelationRequest) Reset() {
	*x = SetRelationRequest{}
	mi := &file_aserto_directory_writer_v3_writer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRelationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRelationRequest) ProtoMessage() {}

func (x *SetRelationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_directory_writer_v3_writer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRelationRequest.ProtoReflect.Descriptor instead.
func (*SetRelationRequest) Descriptor() ([]byte, []int) {
	return file_aserto_directory_writer_v3_writer_proto_rawDescGZIP(), []int{4}
}

func (x *SetRelationRequest) GetRelation() *v3.Relation {
	if x != nil {
		return x.Relation
	}
	return nil
}

type SetRelationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// relation instance
	Result        *v3.Relation `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetRelationResponse) Reset() {
	*x = SetRelationResponse{}
	mi := &file_aserto_directory_writer_v3_writer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetRelationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRelationResponse) ProtoMessage() {}

func (x *SetRelationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_directory_writer_v3_writer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRelationResponse.ProtoReflect.Descriptor instead.
func (*SetRelationResponse) Descriptor() ([]byte, []int) {
	return file_aserto_directory_writer_v3_writer_proto_rawDescGZIP(), []int{5}
}

func (x *SetRelationResponse) GetResult() *v3.Relation {
	if x != nil {
		return x.Result
	}
	return nil
}

type DeleteRelationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// object type
	ObjectType string `protobuf:"bytes,1,opt,name=object_type,json=objectType,proto3" json:"object_type,omitempty"`
	// object identifier
	ObjectId string `protobuf:"bytes,2,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	// object relation name
	Relation string `protobuf:"bytes,3,opt,name=relation,proto3" json:"relation,omitempty"`
	// subject type
	SubjectType string `protobuf:"bytes,4,opt,name=subject_type,json=subjectType,proto3" json:"subject_type,omitempty"`
	// subject identifier
	SubjectId string `protobuf:"bytes,5,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	// optional subject relation name
	SubjectRelation string `protobuf:"bytes,6,opt,name=subject_relation,json=subjectRelation,proto3" json:"subject_relation,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DeleteRelationRequest) Reset() {
	*x = DeleteRelationRequest{}
	mi := &file_aserto_directory_writer_v3_writer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRelationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRelationRequest) ProtoMessage() {}

func (x *DeleteRelationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_directory_writer_v3_writer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRelationRequest.ProtoReflect.Descriptor instead.
func (*DeleteRelationRequest) Descriptor() ([]byte, []int) {
	return file_aserto_directory_writer_v3_writer_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteRelationRequest) GetObjectType() string {
	if x != nil {
		return x.ObjectType
	}
	return ""
}

func (x *DeleteRelationRequest) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *DeleteRelationRequest) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

func (x *DeleteRelationRequest) GetSubjectType() string {
	if x != nil {
		return x.SubjectType
	}
	return ""
}

func (x *DeleteRelationRequest) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *DeleteRelationRequest) GetSubjectRelation() string {
	if x != nil {
		return x.SubjectRelation
	}
	return ""
}

type DeleteRelationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// empty result
	Result        *emptypb.Empty `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRelationResponse) Reset() {
	*x = DeleteRelationResponse{}
	mi := &file_aserto_directory_writer_v3_writer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRelationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRelationResponse) ProtoMessage() {}

func (x *DeleteRelationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_directory_writer_v3_writer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRelationResponse.ProtoReflect.Descriptor instead.
func (*DeleteRelationResponse) Descriptor() ([]byte, []int) {
	return file_aserto_directory_writer_v3_writer_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteRelationResponse) GetResult() *emptypb.Empty {
	if x != nil {
		return x.Result
	}
	return nil
}

type SetManifestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Manifest      *v3.Manifest           `protobuf:"bytes,1,opt,name=manifest,proto3" json:"manifest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetManifestRequest) Reset() {
	*x = SetManifestRequest{}
	mi := &file_aserto_directory_writer_v3_writer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetManifestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetManifestRequest) ProtoMessage() {}

func (x *SetManifestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_directory_writer_v3_writer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetManifestRequest.ProtoReflect.Descriptor instead.
func (*SetManifestRequest) Descriptor() ([]byte, []int) {
	return file_aserto_directory_writer_v3_writer_proto_rawDescGZIP(), []int{8}
}

func (x *SetManifestRequest) GetManifest() *v3.Manifest {
	if x != nil {
		return x.Manifest
	}
	return nil
}

type SetManifestResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// empty result
	Result        *emptypb.Empty `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetManifestResponse) Reset() {
	*x = SetManifestResponse{}
	mi := &file_aserto_directory_writer_v3_writer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetManifestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetManifestResponse) ProtoMessage() {}

func (x *SetManifestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_directory_writer_v3_writer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetManifestResponse.ProtoReflect.Descriptor instead.
func (*SetManifestResponse) Descriptor() ([]byte, []int) {
	return file_aserto_directory_writer_v3_writer_proto_rawDescGZIP(), []int{9}
}

func (x *SetManifestResponse) GetResult() *emptypb.Empty {
	if x != nil {
		return x.Result
	}
	return nil
}

type DeleteManifestRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// empty request
	Empty         *emptypb.Empty `protobuf:"bytes,1,opt,name=empty,proto3" json:"empty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteManifestRequest) Reset() {
	*x = DeleteManifestRequest{}
	mi := &file_aserto_directory_writer_v3_writer_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteManifestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteManifestRequest) ProtoMessage() {}

func (x *DeleteManifestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_directory_writer_v3_writer_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteManifestRequest.ProtoReflect.Descriptor instead.
func (*DeleteManifestRequest) Descriptor() ([]byte, []int) {
	return file_aserto_directory_writer_v3_writer_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteManifestRequest) GetEmpty() *emptypb.Empty {
	if x != nil {
		return x.Empty
	}
	return nil
}

type DeleteManifestResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// empty result
	Result        *emptypb.Empty `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteManifestResponse) Reset() {
	*x = DeleteManifestResponse{}
	mi := &file_aserto_directory_writer_v3_writer_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteManifestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteManifestResponse) ProtoMessage() {}

func (x *DeleteManifestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_directory_writer_v3_writer_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteManifestResponse.ProtoReflect.Descriptor instead.
func (*DeleteManifestResponse) Descriptor() ([]byte, []int) {
	return file_aserto_directory_writer_v3_writer_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteManifestResponse) GetResult() *emptypb.Empty {
	if x != nil {
		return x.Result
	}
	return nil
}

type ImportRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// operation Opcode enum value
	OpCode Opcode `protobuf:"varint,1,opt,name=op_code,json=opCode,proto3,enum=aserto.directory.writer.v3.Opcode" json:"op_code,omitempty"`
	// Types that are valid to be assigned to Msg:
	//
	//	*ImportRequest_Object
	//	*ImportRequest_Relation
	//	*ImportRequest_Manifest
	Msg           isImportRequest_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportRequest) Reset() {
	*x = ImportRequest{}
	mi := &file_aserto_directory_writer_v3_writer_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportRequest) ProtoMessage() {}

func (x *ImportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_directory_writer_v3_writer_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportRequest.ProtoReflect.Descriptor instead.
func (*ImportRequest) Descriptor() ([]byte, []int) {
	return file_aserto_directory_writer_v3_writer_proto_rawDescGZIP(), []int{12}
}

func (x *ImportRequest) GetOpCode() Opcode {
	if x != nil {
		return x.OpCode
	}
	return Opcode_OPCODE_UNKNOWN
}

func (x *ImportRequest) GetMsg() isImportRequest_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ImportRequest) GetObject() *v3.Object {
	if x != nil {
		if x, ok := x.Msg.(*ImportRequest_Object); ok {
			return x.Object
		}
	}
	return nil
}

func (x *ImportRequest) GetRelation() *v3.Relation {
	if x != nil {
		if x, ok := x.Msg.(*ImportRequest_Relation); ok {
			return x.Relation
		}
	}
	return nil
}

func (x *ImportRequest) GetManifest() *v3.Manifest {
	if x != nil {
		if x, ok := x.Msg.(*ImportRequest_Manifest); ok {
			return x.Manifest
		}
	}
	return nil
}

type isImportRequest_Msg interface {
	isImportRequest_Msg()
}

type ImportRequest_Object struct {
	// object import message
	Object *v3.Object `protobuf:"bytes,5,opt,name=object,proto3,oneof"`
}

type ImportRequest_Relation struct {
	// relation import message
	Relation *v3.Relation `protobuf:"bytes,6,opt,name=relation,proto3,oneof"`
}

type ImportRequest_Manifest struct {
	// manifest import message
	Manifest *v3.Manifest `protobuf:"bytes,7,opt,name=manifest,proto3,oneof"`
}

func (*ImportRequest_Object) isImportRequest_Msg() {}

func (*ImportRequest_Relation) isImportRequest_Msg() {}

func (*ImportRequest_Manifest) isImportRequest_Msg() {}

type ImportResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*ImportResponse_Status
	//	*ImportResponse_Counter
	Msg           isImportResponse_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportResponse) Reset() {
	*x = ImportResponse{}
	mi := &file_aserto_directory_writer_v3_writer_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportResponse) ProtoMessage() {}

func (x *ImportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_directory_writer_v3_writer_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportResponse.ProtoReflect.Descriptor instead.
func (*ImportResponse) Descriptor() ([]byte, []int) {
	return file_aserto_directory_writer_v3_writer_proto_rawDescGZIP(), []int{13}
}

func (x *ImportResponse) GetMsg() isImportResponse_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ImportResponse) GetStatus() *ImportStatus {
	if x != nil {
		if x, ok := x.Msg.(*ImportResponse_Status); ok {
			return x.Status
		}
	}
	return nil
}

func (x *ImportResponse) GetCounter() *ImportCounter {
	if x != nil {
		if x, ok := x.Msg.(*ImportResponse_Counter); ok {
			return x.Counter
		}
	}
	return nil
}

type isImportResponse_Msg interface {
	isImportResponse_Msg()
}

type ImportResponse_Status struct {
	// import status message
	Status *ImportStatus `protobuf:"bytes,4,opt,name=status,proto3,oneof"`
}

type ImportResponse_Counter struct {
	// import counter per type
	Counter *ImportCounter `protobuf:"bytes,5,opt,name=counter,proto3,oneof"`
}

func (*ImportResponse_Status) isImportResponse_Msg() {}

func (*ImportResponse_Counter) isImportResponse_Msg() {}

type ImportCounter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// number of messages received
	Recv uint64 `protobuf:"varint,1,opt,name=recv,proto3" json:"recv,omitempty"`
	// number of messages with OPCODE_SET
	Set uint64 `protobuf:"varint,2,opt,name=set,proto3" json:"set,omitempty"`
	// number of messages with OPCODE_DELETE
	Delete uint64 `protobuf:"varint,3,opt,name=delete,proto3" json:"delete,omitempty"`
	// number of messages resulting in error
	Error uint64 `protobuf:"varint,4,opt,name=error,proto3" json:"error,omitempty"`
	// counter of type (object|relation)
	Type          string `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportCounter) Reset() {
	*x = ImportCounter{}
	mi := &file_aserto_directory_writer_v3_writer_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportCounter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportCounter) ProtoMessage() {}

func (x *ImportCounter) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_directory_writer_v3_writer_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportCounter.ProtoReflect.Descriptor instead.
func (*ImportCounter) Descriptor() ([]byte, []int) {
	return file_aserto_directory_writer_v3_writer_proto_rawDescGZIP(), []int{14}
}

func (x *ImportCounter) GetRecv() uint64 {
	if x != nil {
		return x.Recv
	}
	return 0
}

func (x *ImportCounter) GetSet() uint64 {
	if x != nil {
		return x.Set
	}
	return 0
}

func (x *ImportCounter) GetDelete() uint64 {
	if x != nil {
		return x.Delete
	}
	return 0
}

func (x *ImportCounter) GetError() uint64 {
	if x != nil {
		return x.Error
	}
	return 0
}

func (x *ImportCounter) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type ImportStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// gRPC status code (google.golang.org/grpc/codes)
	Code uint32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	// gRPC status message (google.golang.org/grpc/status)
	Msg string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	// req contains the original import request message
	Req           *ImportRequest `protobuf:"bytes,3,opt,name=req,proto3" json:"req,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportStatus) Reset() {
	*x = ImportStatus{}
	mi := &file_aserto_directory_writer_v3_writer_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportStatus) ProtoMessage() {}

func (x *ImportStatus) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_directory_writer_v3_writer_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportStatus.ProtoReflect.Descriptor instead.
func (*ImportStatus) Descriptor() ([]byte, []int) {
	return file_aserto_directory_writer_v3_writer_proto_rawDescGZIP(), []int{15}
}

func (x *ImportStatus) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ImportStatus) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ImportStatus) GetReq() *ImportRequest {
	if x != nil {
		return x.Req
	}
	return nil
}

var File_aserto_directory_writer_v3_writer_proto protoreflect.FileDescriptor

const file_aserto_directory_writer_v3_writer_proto_rawDesc = "" +
	"\n" +
	"'aserto/directory/writer/v3/writer.proto\x12\x1aaserto.directory.writer.v3\x1a'aserto/directory/common/v3/common.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"S\n" +
	"\x10SetObjectRequest\x12?\n" +
	"\x06object\x18\x01 \x01(\v2\".aserto.directory.common.v3.ObjectB\x03\xe0A\x02R\x06object\"O\n" +
	"\x11SetObjectResponse\x12:\n" +
	"\x06result\x18\x01 \x01(\v2\".aserto.directory.common.v3.ObjectR\x06result\"\x89\x01\n" +
	"\x13DeleteObjectRequest\x12$\n" +
	"\vobject_type\x18\x01 \x01(\tB\x03\xe0A\x02R\n" +
	"objectType\x12 \n" +
	"\tobject_id\x18\x02 \x01(\tB\x03\xe0A\x02R\bobjectId\x12*\n" +
	"\x0ewith_relations\x18\x03 \x01(\bB\x03\xe0A\x01R\rwithRelations\"F\n" +
	"\x14DeleteObjectResponse\x12.\n" +
	"\x06result\x18\x01 \x01(\v2\x16.google.protobuf.EmptyR\x06result\"[\n" +
	"\x12SetRelationRequest\x12E\n" +
	"\brelation\x18\x01 \x01(\v2$.aserto.directory.common.v3.RelationB\x03\xe0A\x02R\brelation\"S\n" +
	"\x13SetRelationResponse\x12<\n" +
	"\x06result\x18\x01 \x01(\v2$.aserto.directory.common.v3.RelationR\x06result\"\xfc\x01\n" +
	"\x15DeleteRelationRequest\x12$\n" +
	"\vobject_type\x18\x01 \x01(\tB\x03\xe0A\x02R\n" +
	"objectType\x12 \n" +
	"\tobject_id\x18\x02 \x01(\tB\x03\xe0A\x02R\bobjectId\x12\x1f\n" +
	"\brelation\x18\x03 \x01(\tB\x03\xe0A\x02R\brelation\x12&\n" +
	"\fsubject_type\x18\x04 \x01(\tB\x03\xe0A\x02R\vsubjectType\x12\"\n" +
	"\n" +
	"subject_id\x18\x05 \x01(\tB\x03\xe0A\x02R\tsubjectId\x12.\n" +
	"\x10subject_relation\x18\x06 \x01(\tB\x03\xe0A\x01R\x0fsubjectRelation\"H\n" +
	"\x16DeleteRelationResponse\x12.\n" +
	"\x06result\x18\x01 \x01(\v2\x16.google.protobuf.EmptyR\x06result\"V\n" +
	"\x12SetManifestRequest\x12@\n" +
	"\bmanifest\x18\x01 \x01(\v2$.aserto.directory.common.v3.ManifestR\bmanifest\"E\n" +
	"\x13SetManifestResponse\x12.\n" +
	"\x06result\x18\x01 \x01(\v2\x16.google.protobuf.EmptyR\x06result\"E\n" +
	"\x15DeleteManifestRequest\x12,\n" +
	"\x05empty\x18\x01 \x01(\v2\x16.google.protobuf.EmptyR\x05empty\"H\n" +
	"\x16DeleteManifestResponse\x12.\n" +
	"\x06result\x18\x01 \x01(\v2\x16.google.protobuf.EmptyR\x06result\"\x99\x02\n" +
	"\rImportRequest\x12;\n" +
	"\aop_code\x18\x01 \x01(\x0e2\".aserto.directory.writer.v3.OpcodeR\x06opCode\x12<\n" +
	"\x06object\x18\x05 \x01(\v2\".aserto.directory.common.v3.ObjectH\x00R\x06object\x12B\n" +
	"\brelation\x18\x06 \x01(\v2$.aserto.directory.common.v3.RelationH\x00R\brelation\x12B\n" +
	"\bmanifest\x18\a \x01(\v2$.aserto.directory.common.v3.ManifestH\x00R\bmanifestB\x05\n" +
	"\x03msg\"\xa2\x01\n" +
	"\x0eImportResponse\x12B\n" +
	"\x06status\x18\x04 \x01(\v2(.aserto.directory.writer.v3.ImportStatusH\x00R\x06status\x12E\n" +
	"\acounter\x18\x05 \x01(\v2).aserto.directory.writer.v3.ImportCounterH\x00R\acounterB\x05\n" +
	"\x03msg\"w\n" +
	"\rImportCounter\x12\x12\n" +
	"\x04recv\x18\x01 \x01(\x04R\x04recv\x12\x10\n" +
	"\x03set\x18\x02 \x01(\x04R\x03set\x12\x16\n" +
	"\x06delete\x18\x03 \x01(\x04R\x06delete\x12\x14\n" +
	"\x05error\x18\x04 \x01(\x04R\x05error\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\"q\n" +
	"\fImportStatus\x12\x12\n" +
	"\x04code\x18\x01 \x01(\rR\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12;\n" +
	"\x03req\x18\x03 \x01(\v2).aserto.directory.writer.v3.ImportRequestR\x03req*a\n" +
	"\x06Opcode\x12\x12\n" +
	"\x0eOPCODE_UNKNOWN\x10\x00\x12\x0e\n" +
	"\n" +
	"OPCODE_SET\x10\x01\x12\x11\n" +
	"\rOPCODE_DELETE\x10\x02\x12 \n" +
	"\x1cOPCODE_DELETE_WITH_RELATIONS\x10\x032\xd9\r\n" +
	"\x06Writer\x12\xfa\x01\n" +
	"\tSetObject\x12,.aserto.directory.writer.v3.SetObjectRequest\x1a-.aserto.directory.writer.v3.SetObjectResponse\"\x8f\x01\x92Ai\n" +
	"\tdirectory\x12\n" +
	"Set object\x1a\vSet object.*\x1edirectory.writer.v3.object.setb#\n" +
	"\x13\n" +
	"\x0fDirectoryAPIKey\x12\x00\n" +
	"\f\n" +
	"\bTenantID\x12\x00\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/api/v3/directory/object\x12\xa3\x02\n" +
	"\fDeleteObject\x12/.aserto.directory.writer.v3.DeleteObjectRequest\x1a0.aserto.directory.writer.v3.DeleteObjectResponse\"\xaf\x01\x92Ar\n" +
	"\tdirectory\x12\rDelete object\x1a\x0eDelete object.*!directory.writer.v3.object.deleteb#\n" +
	"\x13\n" +
	"\x0fDirectoryAPIKey\x12\x00\n" +
	"\f\n" +
	"\bTenantID\x12\x00\x82\xd3\xe4\x93\x024*2/api/v3/directory/object/{object_type}/{object_id}\x12\x88\x02\n" +
	"\vSetRelation\x12..aserto.directory.writer.v3.SetRelationRequest\x1a/.aserto.directory.writer.v3.SetRelationResponse\"\x97\x01\x92Ao\n" +
	"\tdirectory\x12\fSet relation\x1a\rSet relation.* directory.writer.v3.relation.setb#\n" +
	"\x13\n" +
	"\x0fDirectoryAPIKey\x12\x00\n" +
	"\f\n" +
	"\bTenantID\x12\x00\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/api/v3/directory/relation\x12\x97\x02\n" +
	"\x0eDeleteRelation\x121.aserto.directory.writer.v3.DeleteRelationRequest\x1a2.aserto.directory.writer.v3.DeleteRelationResponse\"\x9d\x01\x92Ax\n" +
	"\tdirectory\x12\x0fDelete relation\x1a\x10Delete relation.*#directory.writer.v3.relation.deleteb#\n" +
	"\x13\n" +
	"\x0fDirectoryAPIKey\x12\x00\n" +
	"\f\n" +
	"\bTenantID\x12\x00\x82\xd3\xe4\x93\x02\x1c*\x1a/api/v3/directory/relation\x12\x85\x02\n" +
	"\vSetManifest\x12..aserto.directory.writer.v3.SetManifestRequest\x1a/.aserto.directory.writer.v3.SetManifestResponse\"\x94\x01\x92Ao\n" +
	"\tdirectory\x12\fSet manifest\x1a\rSet manifest.* directory.writer.v3.manifest.setb#\n" +
	"\x13\n" +
	"\x0fDirectoryAPIKey\x12\x00\n" +
	"\f\n" +
	"\bTenantID\x12\x00\x82\xd3\xe4\x93\x02\x1c\"\x1a/api/v3/directory/manifest\x12\x97\x02\n" +
	"\x0eDeleteManifest\x121.aserto.directory.writer.v3.DeleteManifestRequest\x1a2.aserto.directory.writer.v3.DeleteManifestResponse\"\x9d\x01\x92Ax\n" +
	"\tdirectory\x12\x0fDelete manifest\x1a\x10Delete manifest.*#directory.writer.v3.manifest.deleteb#\n" +
	"\x13\n" +
	"\x0fDirectoryAPIKey\x12\x00\n" +
	"\f\n" +
	"\bTenantID\x12\x00\x82\xd3\xe4\x93\x02\x1c*\x1a/api/v3/directory/manifest\x12e\n" +
	"\x06Import\x12).aserto.directory.writer.v3.ImportRequest\x1a*.aserto.directory.writer.v3.ImportResponse\"\x00(\x010\x01BFZDgithub.com/aserto-dev/go-directory/aserto/directory/writer/v3;writerb\x06proto3"

var (
	file_aserto_directory_writer_v3_writer_proto_rawDescOnce sync.Once
	file_aserto_directory_writer_v3_writer_proto_rawDescData []byte
)

func file_aserto_directory_writer_v3_writer_proto_rawDescGZIP() []byte {
	file_aserto_directory_writer_v3_writer_proto_rawDescOnce.Do(func() {
		file_aserto_directory_writer_v3_writer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aserto_directory_writer_v3_writer_proto_rawDesc), len(file_aserto_directory_writer_v3_writer_proto_rawDesc)))
	})
	return file_aserto_directory_writer_v3_writer_proto_rawDescData
}

var file_aserto_directory_writer_v3_writer_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_aserto_directory_writer_v3_writer_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_aserto_directory_writer_v3_writer_proto_goTypes = []any{
	(Opcode)(0),                    // 0: aserto.directory.writer.v3.Opcode
	(*SetObjectRequest)(nil),       // 1: aserto.directory.writer.v3.SetObjectRequest
	(*SetObjectResponse)(nil),      // 2: aserto.directory.writer.v3.SetObjectResponse
	(*DeleteObjectRequest)(nil),    // 3: aserto.directory.writer.v3.DeleteObjectRequest
	(*DeleteObjectResponse)(nil),   // 4: aserto.directory.writer.v3.DeleteObjectResponse
	(*SetRelationRequest)(nil),     // 5: aserto.directory.writer.v3.SetRelationRequest
	(*SetRelationResponse)(nil),    // 6: aserto.directory.writer.v3.SetRelationResponse
	(*DeleteRelationRequest)(nil),  // 7: aserto.directory.writer.v3.DeleteRelationRequest
	(*DeleteRelationResponse)(nil), // 8: aserto.directory.writer.v3.DeleteRelationResponse
	(*SetManifestRequest)(nil),     // 9: aserto.directory.writer.v3.SetManifestRequest
	(*SetManifestResponse)(nil),    // 10: aserto.directory.writer.v3.SetManifestResponse
	(*DeleteManifestRequest)(nil),  // 11: aserto.directory.writer.v3.DeleteManifestRequest
	(*DeleteManifestResponse)(nil), // 12: aserto.directory.writer.v3.DeleteManifestResponse
	(*ImportRequest)(nil),          // 13: aserto.directory.writer.v3.ImportRequest
	(*ImportResponse)(nil),         // 14: aserto.directory.writer.v3.ImportResponse
	(*ImportCounter)(nil),          // 15: aserto.directory.writer.v3.ImportCounter
	(*ImportStatus)(nil),           // 16: aserto.directory.writer.v3.ImportStatus
	(*v3.Object)(nil),              // 17: aserto.directory.common.v3.Object
	(*emptypb.Empty)(nil),          // 18: google.protobuf.Empty
	(*v3.Relation)(nil),            // 19: aserto.directory.common.v3.Relation
	(*v3.Manifest)(nil),            // 20: aserto.directory.common.v3.Manifest
}
var file_aserto_directory_writer_v3_writer_proto_depIdxs = []int32{
	17, // 0: aserto.directory.writer.v3.SetObjectRequest.object:type_name -> aserto.directory.common.v3.Object
	17, // 1: aserto.directory.writer.v3.SetObjectResponse.result:type_name -> aserto.directory.common.v3.Object
	18, // 2: aserto.directory.writer.v3.DeleteObjectResponse.result:type_name -> google.protobuf.Empty
	19, // 3: aserto.directory.writer.v3.SetRelationRequest.relation:type_name -> aserto.directory.common.v3.Relation
	19, // 4: aserto.directory.writer.v3.SetRelationResponse.result:type_name -> aserto.directory.common.v3.Relation
	18, // 5: aserto.directory.writer.v3.DeleteRelationResponse.result:type_name -> google.protobuf.Empty
	20, // 6: aserto.directory.writer.v3.SetManifestRequest.manifest:type_name -> aserto.directory.common.v3.Manifest
	18, // 7: aserto.directory.writer.v3.SetManifestResponse.result:type_name -> google.protobuf.Empty
	18, // 8: aserto.directory.writer.v3.DeleteManifestRequest.empty:type_name -> google.protobuf.Empty
	18, // 9: aserto.directory.writer.v3.DeleteManifestResponse.result:type_name -> google.protobuf.Empty
	0,  // 10: aserto.directory.writer.v3.ImportRequest.op_code:type_name -> aserto.directory.writer.v3.Opcode
	17, // 11: aserto.directory.writer.v3.ImportRequest.object:type_name -> aserto.directory.common.v3.Object
	19, // 12: aserto.directory.writer.v3.ImportRequest.relation:type_name -> aserto.directory.common.v3.Relation
	20, // 13: aserto.directory.writer.v3.ImportRequest.manifest:type_name -> aserto.directory.common.v3.Manifest
	16, // 14: aserto.directory.writer.v3.ImportResponse.status:type_name -> aserto.directory.writer.v3.ImportStatus
	15, // 15: aserto.directory.writer.v3.ImportResponse.counter:type_name -> aserto.directory.writer.v3.ImportCounter
	13, // 16: aserto.directory.writer.v3.ImportStatus.req:type_name -> aserto.directory.writer.v3.ImportRequest
	1,  // 17: aserto.directory.writer.v3.Writer.SetObject:input_type -> aserto.directory.writer.v3.SetObjectRequest
	3,  // 18: aserto.directory.writer.v3.Writer.DeleteObject:input_type -> aserto.directory.writer.v3.DeleteObjectRequest
	5,  // 19: aserto.directory.writer.v3.Writer.SetRelation:input_type -> aserto.directory.writer.v3.SetRelationRequest
	7,  // 20: aserto.directory.writer.v3.Writer.DeleteRelation:input_type -> aserto.directory.writer.v3.DeleteRelationRequest
	9,  // 21: aserto.directory.writer.v3.Writer.SetManifest:input_type -> aserto.directory.writer.v3.SetManifestRequest
	11, // 22: aserto.directory.writer.v3.Writer.DeleteManifest:input_type -> aserto.directory.writer.v3.DeleteManifestRequest
	13, // 23: aserto.directory.writer.v3.Writer.Import:input_type -> aserto.directory.writer.v3.ImportRequest
	2,  // 24: aserto.directory.writer.v3.Writer.SetObject:output_type -> aserto.directory.writer.v3.SetObjectResponse
	4,  // 25: aserto.directory.writer.v3.Writer.DeleteObject:output_type -> aserto.directory.writer.v3.DeleteObjectResponse
	6,  // 26: aserto.directory.writer.v3.Writer.SetRelation:output_type -> aserto.directory.writer.v3.SetRelationResponse
	8,  // 27: aserto.directory.writer.v3.Writer.DeleteRelation:output_type -> aserto.directory.writer.v3.DeleteRelationResponse
	10, // 28: aserto.directory.writer.v3.Writer.SetManifest:output_type -> aserto.directory.writer.v3.SetManifestResponse
	12, // 29: aserto.directory.writer.v3.Writer.DeleteManifest:output_type -> aserto.directory.writer.v3.DeleteManifestResponse
	14, // 30: aserto.directory.writer.v3.Writer.Import:output_type -> aserto.directory.writer.v3.ImportResponse
	24, // [24:31] is the sub-list for method output_type
	17, // [17:24] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_aserto_directory_writer_v3_writer_proto_init() }
func file_aserto_directory_writer_v3_writer_proto_init() {
	if File_aserto_directory_writer_v3_writer_proto != nil {
		return
	}
	file_aserto_directory_writer_v3_writer_proto_msgTypes[12].OneofWrappers = []any{
		(*ImportRequest_Object)(nil),
		(*ImportRequest_Relation)(nil),
		(*ImportRequest_Manifest)(nil),
	}
	file_aserto_directory_writer_v3_writer_proto_msgTypes[13].OneofWrappers = []any{
		(*ImportResponse_Status)(nil),
		(*ImportResponse_Counter)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aserto_directory_writer_v3_writer_proto_rawDesc), len(file_aserto_directory_writer_v3_writer_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_aserto_directory_writer_v3_writer_proto_goTypes,
		DependencyIndexes: file_aserto_directory_writer_v3_writer_proto_depIdxs,
		EnumInfos:         file_aserto_directory_writer_v3_writer_proto_enumTypes,
		MessageInfos:      file_aserto_directory_writer_v3_writer_proto_msgTypes,
	}.Build()
	File_aserto_directory_writer_v3_writer_proto = out.File
	file_aserto_directory_writer_v3_writer_proto_goTypes = nil
	file_aserto_directory_writer_v3_writer_proto_depIdxs = nil
}
