// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: aserto/directory/reader/v4/reader.proto

package reader

import (
	v4 "github.com/aserto-dev/go-directory/aserto/directory/common/v4"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Option int32

const (
	// nothing selected (default initialization value)
	Option_OPTION_UNKNOWN Option = 0
	// manifest instances
	Option_OPTION_DATA_MANIFEST Option = 1
	// model instances
	Option_OPTION_DATA_MODEL Option = 2
	// object instances
	Option_OPTION_DATA_OBJECTS Option = 8
	// relation instances
	Option_OPTION_DATA_RELATIONS Option = 16
	// all data = OPTION_DATA_OBJECTS | OPTION_DATA_RELATIONS
	Option_OPTION_DATA Option = 24
	// stats
	Option_OPTION_STATS Option = 64
)

// Enum value maps for Option.
var (
	Option_name = map[int32]string{
		0:  "OPTION_UNKNOWN",
		1:  "OPTION_DATA_MANIFEST",
		2:  "OPTION_DATA_MODEL",
		8:  "OPTION_DATA_OBJECTS",
		16: "OPTION_DATA_RELATIONS",
		24: "OPTION_DATA",
		64: "OPTION_STATS",
	}
	Option_value = map[string]int32{
		"OPTION_UNKNOWN":        0,
		"OPTION_DATA_MANIFEST":  1,
		"OPTION_DATA_MODEL":     2,
		"OPTION_DATA_OBJECTS":   8,
		"OPTION_DATA_RELATIONS": 16,
		"OPTION_DATA":           24,
		"OPTION_STATS":          64,
	}
)

func (x Option) Enum() *Option {
	p := new(Option)
	*p = x
	return p
}

func (x Option) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Option) Descriptor() protoreflect.EnumDescriptor {
	return file_aserto_directory_reader_v4_reader_proto_enumTypes[0].Descriptor()
}

func (Option) Type() protoreflect.EnumType {
	return &file_aserto_directory_reader_v4_reader_proto_enumTypes[0]
}

func (x Option) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Option.Descriptor instead.
func (Option) EnumDescriptor() ([]byte, []int) {
	return file_aserto_directory_reader_v4_reader_proto_rawDescGZIP(), []int{0}
}

type GetManifestRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// empty request
	Empty         *emptypb.Empty `protobuf:"bytes,1,opt,name=empty,proto3" json:"empty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetManifestRequest) Reset() {
	*x = GetManifestRequest{}
	mi := &file_aserto_directory_reader_v4_reader_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetManifestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetManifestRequest) ProtoMessage() {}

func (x *GetManifestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_directory_reader_v4_reader_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetManifestRequest.ProtoReflect.Descriptor instead.
func (*GetManifestRequest) Descriptor() ([]byte, []int) {
	return file_aserto_directory_reader_v4_reader_proto_rawDescGZIP(), []int{0}
}

func (x *GetManifestRequest) GetEmpty() *emptypb.Empty {
	if x != nil {
		return x.Empty
	}
	return nil
}

type GetManifestResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// manifest instance
	Result        *v4.Manifest `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetManifestResponse) Reset() {
	*x = GetManifestResponse{}
	mi := &file_aserto_directory_reader_v4_reader_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetManifestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetManifestResponse) ProtoMessage() {}

func (x *GetManifestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_directory_reader_v4_reader_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetManifestResponse.ProtoReflect.Descriptor instead.
func (*GetManifestResponse) Descriptor() ([]byte, []int) {
	return file_aserto_directory_reader_v4_reader_proto_rawDescGZIP(), []int{1}
}

func (x *GetManifestResponse) GetResult() *v4.Manifest {
	if x != nil {
		return x.Result
	}
	return nil
}

type GetModelRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// empty request
	Empty         *emptypb.Empty `protobuf:"bytes,1,opt,name=empty,proto3" json:"empty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModelRequest) Reset() {
	*x = GetModelRequest{}
	mi := &file_aserto_directory_reader_v4_reader_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelRequest) ProtoMessage() {}

func (x *GetModelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_directory_reader_v4_reader_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModelRequest.ProtoReflect.Descriptor instead.
func (*GetModelRequest) Descriptor() ([]byte, []int) {
	return file_aserto_directory_reader_v4_reader_proto_rawDescGZIP(), []int{2}
}

func (x *GetModelRequest) GetEmpty() *emptypb.Empty {
	if x != nil {
		return x.Empty
	}
	return nil
}

type GetModelResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// model instance
	Result        *v4.Model `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModelResponse) Reset() {
	*x = GetModelResponse{}
	mi := &file_aserto_directory_reader_v4_reader_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelResponse) ProtoMessage() {}

func (x *GetModelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_directory_reader_v4_reader_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModelResponse.ProtoReflect.Descriptor instead.
func (*GetModelResponse) Descriptor() ([]byte, []int) {
	return file_aserto_directory_reader_v4_reader_proto_rawDescGZIP(), []int{3}
}

func (x *GetModelResponse) GetResult() *v4.Model {
	if x != nil {
		return x.Result
	}
	return nil
}

type GetObjectRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// object type identifier
	ObjectType string `protobuf:"bytes,1,opt,name=object_type,json=objectType,proto3" json:"object_type,omitempty"`
	// object instance identifier
	ObjectId string `protobuf:"bytes,2,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	// materialize the object relations objects (optional)
	WithRelations bool `protobuf:"varint,3,opt,name=with_relations,json=withRelations,proto3" json:"with_relations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetObjectRequest) Reset() {
	*x = GetObjectRequest{}
	mi := &file_aserto_directory_reader_v4_reader_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObjectRequest) ProtoMessage() {}

func (x *GetObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_directory_reader_v4_reader_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObjectRequest.ProtoReflect.Descriptor instead.
func (*GetObjectRequest) Descriptor() ([]byte, []int) {
	return file_aserto_directory_reader_v4_reader_proto_rawDescGZIP(), []int{4}
}

func (x *GetObjectRequest) GetObjectType() string {
	if x != nil {
		return x.ObjectType
	}
	return ""
}

func (x *GetObjectRequest) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *GetObjectRequest) GetWithRelations() bool {
	if x != nil {
		return x.WithRelations
	}
	return false
}

type GetObjectResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// object instance
	Result *v4.Object `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	// array of associated relations of given object instance
	Relations     []*v4.Relation `protobuf:"bytes,4,rep,name=relations,proto3" json:"relations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetObjectResponse) Reset() {
	*x = GetObjectResponse{}
	mi := &file_aserto_directory_reader_v4_reader_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetObjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObjectResponse) ProtoMessage() {}

func (x *GetObjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_directory_reader_v4_reader_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObjectResponse.ProtoReflect.Descriptor instead.
func (*GetObjectResponse) Descriptor() ([]byte, []int) {
	return file_aserto_directory_reader_v4_reader_proto_rawDescGZIP(), []int{5}
}

func (x *GetObjectResponse) GetResult() *v4.Object {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *GetObjectResponse) GetRelations() []*v4.Relation {
	if x != nil {
		return x.Relations
	}
	return nil
}

type GetObjectsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// array of object identifiers
	Param         []*v4.ObjectIdentifier `protobuf:"bytes,1,rep,name=param,proto3" json:"param,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetObjectsRequest) Reset() {
	*x = GetObjectsRequest{}
	mi := &file_aserto_directory_reader_v4_reader_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetObjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObjectsRequest) ProtoMessage() {}

func (x *GetObjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_directory_reader_v4_reader_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObjectsRequest.ProtoReflect.Descriptor instead.
func (*GetObjectsRequest) Descriptor() ([]byte, []int) {
	return file_aserto_directory_reader_v4_reader_proto_rawDescGZIP(), []int{6}
}

func (x *GetObjectsRequest) GetParam() []*v4.ObjectIdentifier {
	if x != nil {
		return x.Param
	}
	return nil
}

type GetObjectsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// array of object instances
	Results       []*v4.Object `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetObjectsResponse) Reset() {
	*x = GetObjectsResponse{}
	mi := &file_aserto_directory_reader_v4_reader_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetObjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObjectsResponse) ProtoMessage() {}

func (x *GetObjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_directory_reader_v4_reader_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObjectsResponse.ProtoReflect.Descriptor instead.
func (*GetObjectsResponse) Descriptor() ([]byte, []int) {
	return file_aserto_directory_reader_v4_reader_proto_rawDescGZIP(), []int{7}
}

func (x *GetObjectsResponse) GetResults() []*v4.Object {
	if x != nil {
		return x.Results
	}
	return nil
}

type ListObjectsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// object type identifier (optional)
	ObjectType string `protobuf:"bytes,1,opt,name=object_type,json=objectType,proto3" json:"object_type,omitempty"`
	// pagination request (optional)
	Page          *v4.PaginationRequest `protobuf:"bytes,9,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListObjectsRequest) Reset() {
	*x = ListObjectsRequest{}
	mi := &file_aserto_directory_reader_v4_reader_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListObjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListObjectsRequest) ProtoMessage() {}

func (x *ListObjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_directory_reader_v4_reader_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListObjectsRequest.ProtoReflect.Descriptor instead.
func (*ListObjectsRequest) Descriptor() ([]byte, []int) {
	return file_aserto_directory_reader_v4_reader_proto_rawDescGZIP(), []int{8}
}

func (x *ListObjectsRequest) GetObjectType() string {
	if x != nil {
		return x.ObjectType
	}
	return ""
}

func (x *ListObjectsRequest) GetPage() *v4.PaginationRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListObjectsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// array of object instances
	Results []*v4.Object `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	// pagination response
	Page          *v4.PaginationResponse `protobuf:"bytes,9,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListObjectsResponse) Reset() {
	*x = ListObjectsResponse{}
	mi := &file_aserto_directory_reader_v4_reader_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListObjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListObjectsResponse) ProtoMessage() {}

func (x *ListObjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_directory_reader_v4_reader_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListObjectsResponse.ProtoReflect.Descriptor instead.
func (*ListObjectsResponse) Descriptor() ([]byte, []int) {
	return file_aserto_directory_reader_v4_reader_proto_rawDescGZIP(), []int{9}
}

func (x *ListObjectsResponse) GetResults() []*v4.Object {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *ListObjectsResponse) GetPage() *v4.PaginationResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

type GetRelationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// object type identifier
	ObjectType string `protobuf:"bytes,1,opt,name=object_type,json=objectType,proto3" json:"object_type,omitempty"`
	// object instance identifier
	ObjectId string `protobuf:"bytes,2,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	// relation name
	Relation string `protobuf:"bytes,3,opt,name=relation,proto3" json:"relation,omitempty"`
	// subject type identifier
	SubjectType string `protobuf:"bytes,4,opt,name=subject_type,json=subjectType,proto3" json:"subject_type,omitempty"`
	// subject instance identifier
	SubjectId string `protobuf:"bytes,5,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	// subject relation name (optional)
	SubjectRelation string `protobuf:"bytes,6,opt,name=subject_relation,json=subjectRelation,proto3" json:"subject_relation,omitempty"`
	// materialize relation objects (optional)
	WithObjects   bool `protobuf:"varint,7,opt,name=with_objects,json=withObjects,proto3" json:"with_objects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRelationRequest) Reset() {
	*x = GetRelationRequest{}
	mi := &file_aserto_directory_reader_v4_reader_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRelationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRelationRequest) ProtoMessage() {}

func (x *GetRelationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_directory_reader_v4_reader_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRelationRequest.ProtoReflect.Descriptor instead.
func (*GetRelationRequest) Descriptor() ([]byte, []int) {
	return file_aserto_directory_reader_v4_reader_proto_rawDescGZIP(), []int{10}
}

func (x *GetRelationRequest) GetObjectType() string {
	if x != nil {
		return x.ObjectType
	}
	return ""
}

func (x *GetRelationRequest) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *GetRelationRequest) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

func (x *GetRelationRequest) GetSubjectType() string {
	if x != nil {
		return x.SubjectType
	}
	return ""
}

func (x *GetRelationRequest) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *GetRelationRequest) GetSubjectRelation() string {
	if x != nil {
		return x.SubjectRelation
	}
	return ""
}

func (x *GetRelationRequest) GetWithObjects() bool {
	if x != nil {
		return x.WithObjects
	}
	return false
}

type GetRelationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// relation instance
	Result *v4.Relation `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	// object instance, set when with_objects=true
	Object *v4.Object `protobuf:"bytes,2,opt,name=object,proto3" json:"object,omitempty"`
	// subject instance, set when with_objects=true
	Subject       *v4.Object `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRelationResponse) Reset() {
	*x = GetRelationResponse{}
	mi := &file_aserto_directory_reader_v4_reader_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRelationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRelationResponse) ProtoMessage() {}

func (x *GetRelationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_directory_reader_v4_reader_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRelationResponse.ProtoReflect.Descriptor instead.
func (*GetRelationResponse) Descriptor() ([]byte, []int) {
	return file_aserto_directory_reader_v4_reader_proto_rawDescGZIP(), []int{11}
}

func (x *GetRelationResponse) GetResult() *v4.Relation {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *GetRelationResponse) GetObject() *v4.Object {
	if x != nil {
		return x.Object
	}
	return nil
}

func (x *GetRelationResponse) GetSubject() *v4.Object {
	if x != nil {
		return x.Subject
	}
	return nil
}

type GetRelationsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// array of relation identifiers
	Param         []*v4.RelationIdentifier `protobuf:"bytes,1,rep,name=param,proto3" json:"param,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRelationsRequest) Reset() {
	*x = GetRelationsRequest{}
	mi := &file_aserto_directory_reader_v4_reader_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRelationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRelationsRequest) ProtoMessage() {}

func (x *GetRelationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_directory_reader_v4_reader_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRelationsRequest.ProtoReflect.Descriptor instead.
func (*GetRelationsRequest) Descriptor() ([]byte, []int) {
	return file_aserto_directory_reader_v4_reader_proto_rawDescGZIP(), []int{12}
}

func (x *GetRelationsRequest) GetParam() []*v4.RelationIdentifier {
	if x != nil {
		return x.Param
	}
	return nil
}

type GetRelationsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// array of relation instances
	Results       []*v4.Relation `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRelationsResponse) Reset() {
	*x = GetRelationsResponse{}
	mi := &file_aserto_directory_reader_v4_reader_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRelationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRelationsResponse) ProtoMessage() {}

func (x *GetRelationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_directory_reader_v4_reader_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRelationsResponse.ProtoReflect.Descriptor instead.
func (*GetRelationsResponse) Descriptor() ([]byte, []int) {
	return file_aserto_directory_reader_v4_reader_proto_rawDescGZIP(), []int{13}
}

func (x *GetRelationsResponse) GetResults() []*v4.Relation {
	if x != nil {
		return x.Results
	}
	return nil
}

type ListRelationsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// object type identifier (optional)
	ObjectType string `protobuf:"bytes,1,opt,name=object_type,json=objectType,proto3" json:"object_type,omitempty"`
	// object instance identifier (optional)
	ObjectId string `protobuf:"bytes,2,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	// relation name (optional)
	Relation string `protobuf:"bytes,3,opt,name=relation,proto3" json:"relation,omitempty"`
	// subject type identifier (optional)
	SubjectType string `protobuf:"bytes,4,opt,name=subject_type,json=subjectType,proto3" json:"subject_type,omitempty"`
	// subject instance identifier (optional)
	SubjectId string `protobuf:"bytes,5,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	// subject relation name (optional)
	SubjectRelation string `protobuf:"bytes,6,opt,name=subject_relation,json=subjectRelation,proto3" json:"subject_relation,omitempty"`
	// materialize relation objects (optional)
	WithObjects bool `protobuf:"varint,7,opt,name=with_objects,json=withObjects,proto3" json:"with_objects,omitempty"`
	// only return relations that do not have a subject relation. (optional)
	WithEmptySubjectRelation bool `protobuf:"varint,8,opt,name=with_empty_subject_relation,json=withEmptySubjectRelation,proto3" json:"with_empty_subject_relation,omitempty"`
	// pagination request (optional)
	Page          *v4.PaginationRequest `protobuf:"bytes,9,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRelationsRequest) Reset() {
	*x = ListRelationsRequest{}
	mi := &file_aserto_directory_reader_v4_reader_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRelationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRelationsRequest) ProtoMessage() {}

func (x *ListRelationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_directory_reader_v4_reader_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRelationsRequest.ProtoReflect.Descriptor instead.
func (*ListRelationsRequest) Descriptor() ([]byte, []int) {
	return file_aserto_directory_reader_v4_reader_proto_rawDescGZIP(), []int{14}
}

func (x *ListRelationsRequest) GetObjectType() string {
	if x != nil {
		return x.ObjectType
	}
	return ""
}

func (x *ListRelationsRequest) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *ListRelationsRequest) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

func (x *ListRelationsRequest) GetSubjectType() string {
	if x != nil {
		return x.SubjectType
	}
	return ""
}

func (x *ListRelationsRequest) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *ListRelationsRequest) GetSubjectRelation() string {
	if x != nil {
		return x.SubjectRelation
	}
	return ""
}

func (x *ListRelationsRequest) GetWithObjects() bool {
	if x != nil {
		return x.WithObjects
	}
	return false
}

func (x *ListRelationsRequest) GetWithEmptySubjectRelation() bool {
	if x != nil {
		return x.WithEmptySubjectRelation
	}
	return false
}

func (x *ListRelationsRequest) GetPage() *v4.PaginationRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListRelationsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// array of relation instances
	Results []*v4.Relation `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	// map of materialized relation objects
	Objects map[string]*v4.Object `protobuf:"bytes,2,rep,name=objects,proto3" json:"objects,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// pagination response
	Page          *v4.PaginationResponse `protobuf:"bytes,9,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRelationsResponse) Reset() {
	*x = ListRelationsResponse{}
	mi := &file_aserto_directory_reader_v4_reader_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRelationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRelationsResponse) ProtoMessage() {}

func (x *ListRelationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_directory_reader_v4_reader_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRelationsResponse.ProtoReflect.Descriptor instead.
func (*ListRelationsResponse) Descriptor() ([]byte, []int) {
	return file_aserto_directory_reader_v4_reader_proto_rawDescGZIP(), []int{15}
}

func (x *ListRelationsResponse) GetResults() []*v4.Relation {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *ListRelationsResponse) GetObjects() map[string]*v4.Object {
	if x != nil {
		return x.Objects
	}
	return nil
}

func (x *ListRelationsResponse) GetPage() *v4.PaginationResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

type CheckRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// object type identifier
	ObjectType string `protobuf:"bytes,1,opt,name=object_type,json=objectType,proto3" json:"object_type,omitempty"`
	// object instance identifier
	ObjectId string `protobuf:"bytes,2,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	// relation name
	Relation string `protobuf:"bytes,3,opt,name=relation,proto3" json:"relation,omitempty"`
	// subject type identifier
	SubjectType string `protobuf:"bytes,4,opt,name=subject_type,json=subjectType,proto3" json:"subject_type,omitempty"`
	// subject instance identifier
	SubjectId string `protobuf:"bytes,5,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	// collect trace information (optional)
	Trace         bool `protobuf:"varint,7,opt,name=trace,proto3" json:"trace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRequest) Reset() {
	*x = CheckRequest{}
	mi := &file_aserto_directory_reader_v4_reader_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRequest) ProtoMessage() {}

func (x *CheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_directory_reader_v4_reader_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRequest.ProtoReflect.Descriptor instead.
func (*CheckRequest) Descriptor() ([]byte, []int) {
	return file_aserto_directory_reader_v4_reader_proto_rawDescGZIP(), []int{16}
}

func (x *CheckRequest) GetObjectType() string {
	if x != nil {
		return x.ObjectType
	}
	return ""
}

func (x *CheckRequest) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *CheckRequest) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

func (x *CheckRequest) GetSubjectType() string {
	if x != nil {
		return x.SubjectType
	}
	return ""
}

func (x *CheckRequest) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *CheckRequest) GetTrace() bool {
	if x != nil {
		return x.Trace
	}
	return false
}

type CheckResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// check result
	Check bool `protobuf:"varint,1,opt,name=check,proto3" json:"check,omitempty"`
	// trace information
	Trace []string `protobuf:"bytes,2,rep,name=trace,proto3" json:"trace,omitempty"`
	// context
	Context       *structpb.Struct `protobuf:"bytes,3,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckResponse) Reset() {
	*x = CheckResponse{}
	mi := &file_aserto_directory_reader_v4_reader_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResponse) ProtoMessage() {}

func (x *CheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_directory_reader_v4_reader_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResponse.ProtoReflect.Descriptor instead.
func (*CheckResponse) Descriptor() ([]byte, []int) {
	return file_aserto_directory_reader_v4_reader_proto_rawDescGZIP(), []int{17}
}

func (x *CheckResponse) GetCheck() bool {
	if x != nil {
		return x.Check
	}
	return false
}

func (x *CheckResponse) GetTrace() []string {
	if x != nil {
		return x.Trace
	}
	return nil
}

func (x *CheckResponse) GetContext() *structpb.Struct {
	if x != nil {
		return x.Context
	}
	return nil
}

type ChecksRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// default values
	Default *CheckRequest `protobuf:"bytes,1,opt,name=default,proto3" json:"default,omitempty"`
	// array of check requests
	Checks        []*CheckRequest `protobuf:"bytes,2,rep,name=checks,proto3" json:"checks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChecksRequest) Reset() {
	*x = ChecksRequest{}
	mi := &file_aserto_directory_reader_v4_reader_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChecksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChecksRequest) ProtoMessage() {}

func (x *ChecksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_directory_reader_v4_reader_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChecksRequest.ProtoReflect.Descriptor instead.
func (*ChecksRequest) Descriptor() ([]byte, []int) {
	return file_aserto_directory_reader_v4_reader_proto_rawDescGZIP(), []int{18}
}

func (x *ChecksRequest) GetDefault() *CheckRequest {
	if x != nil {
		return x.Default
	}
	return nil
}

func (x *ChecksRequest) GetChecks() []*CheckRequest {
	if x != nil {
		return x.Checks
	}
	return nil
}

type ChecksResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// array of check responses
	Checks        []*CheckResponse `protobuf:"bytes,1,rep,name=checks,proto3" json:"checks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChecksResponse) Reset() {
	*x = ChecksResponse{}
	mi := &file_aserto_directory_reader_v4_reader_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChecksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChecksResponse) ProtoMessage() {}

func (x *ChecksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_directory_reader_v4_reader_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChecksResponse.ProtoReflect.Descriptor instead.
func (*ChecksResponse) Descriptor() ([]byte, []int) {
	return file_aserto_directory_reader_v4_reader_proto_rawDescGZIP(), []int{19}
}

func (x *ChecksResponse) GetChecks() []*CheckResponse {
	if x != nil {
		return x.Checks
	}
	return nil
}

type GetGraphRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// object type identifier
	ObjectType string `protobuf:"bytes,1,opt,name=object_type,json=objectType,proto3" json:"object_type,omitempty"`
	// object instance identifier (optional)
	ObjectId string `protobuf:"bytes,2,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	// relation name
	Relation string `protobuf:"bytes,3,opt,name=relation,proto3" json:"relation,omitempty"`
	// subject type identifier
	SubjectType string `protobuf:"bytes,4,opt,name=subject_type,json=subjectType,proto3" json:"subject_type,omitempty"`
	// subject instance identifier (optional)
	SubjectId string `protobuf:"bytes,5,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	// subject relation name (optional)
	SubjectRelation string `protobuf:"bytes,6,opt,name=subject_relation,json=subjectRelation,proto3" json:"subject_relation,omitempty"`
	// return graph paths for each result (optional)
	Explain bool `protobuf:"varint,7,opt,name=explain,proto3" json:"explain,omitempty"`
	// collect trace information (optional)
	Trace         bool `protobuf:"varint,8,opt,name=trace,proto3" json:"trace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGraphRequest) Reset() {
	*x = GetGraphRequest{}
	mi := &file_aserto_directory_reader_v4_reader_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGraphRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGraphRequest) ProtoMessage() {}

func (x *GetGraphRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_directory_reader_v4_reader_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGraphRequest.ProtoReflect.Descriptor instead.
func (*GetGraphRequest) Descriptor() ([]byte, []int) {
	return file_aserto_directory_reader_v4_reader_proto_rawDescGZIP(), []int{20}
}

func (x *GetGraphRequest) GetObjectType() string {
	if x != nil {
		return x.ObjectType
	}
	return ""
}

func (x *GetGraphRequest) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *GetGraphRequest) GetRelation() string {
	if x != nil {
		return x.Relation
	}
	return ""
}

func (x *GetGraphRequest) GetSubjectType() string {
	if x != nil {
		return x.SubjectType
	}
	return ""
}

func (x *GetGraphRequest) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *GetGraphRequest) GetSubjectRelation() string {
	if x != nil {
		return x.SubjectRelation
	}
	return ""
}

func (x *GetGraphRequest) GetExplain() bool {
	if x != nil {
		return x.Explain
	}
	return false
}

func (x *GetGraphRequest) GetTrace() bool {
	if x != nil {
		return x.Trace
	}
	return false
}

type GetGraphResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// matching object identifiers
	Results []*v4.ObjectIdentifier `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	// explanation of results
	Explanation *structpb.Struct `protobuf:"bytes,2,opt,name=explanation,proto3" json:"explanation,omitempty"`
	// trace information
	Trace         []string `protobuf:"bytes,3,rep,name=trace,proto3" json:"trace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGraphResponse) Reset() {
	*x = GetGraphResponse{}
	mi := &file_aserto_directory_reader_v4_reader_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGraphResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGraphResponse) ProtoMessage() {}

func (x *GetGraphResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_directory_reader_v4_reader_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGraphResponse.ProtoReflect.Descriptor instead.
func (*GetGraphResponse) Descriptor() ([]byte, []int) {
	return file_aserto_directory_reader_v4_reader_proto_rawDescGZIP(), []int{21}
}

func (x *GetGraphResponse) GetResults() []*v4.ObjectIdentifier {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *GetGraphResponse) GetExplanation() *structpb.Struct {
	if x != nil {
		return x.Explanation
	}
	return nil
}

func (x *GetGraphResponse) GetTrace() []string {
	if x != nil {
		return x.Trace
	}
	return nil
}

type ExportRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// data export options mask
	Options uint32 `protobuf:"varint,1,opt,name=options,proto3" json:"options,omitempty"`
	// start export from timestamp (UTC)
	StartFrom     *timestamppb.Timestamp `protobuf:"bytes,20,opt,name=start_from,json=startFrom,proto3" json:"start_from,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportRequest) Reset() {
	*x = ExportRequest{}
	mi := &file_aserto_directory_reader_v4_reader_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportRequest) ProtoMessage() {}

func (x *ExportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_directory_reader_v4_reader_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportRequest.ProtoReflect.Descriptor instead.
func (*ExportRequest) Descriptor() ([]byte, []int) {
	return file_aserto_directory_reader_v4_reader_proto_rawDescGZIP(), []int{22}
}

func (x *ExportRequest) GetOptions() uint32 {
	if x != nil {
		return x.Options
	}
	return 0
}

func (x *ExportRequest) GetStartFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.StartFrom
	}
	return nil
}

type ExportResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*ExportResponse_Manifest
	//	*ExportResponse_Model
	//	*ExportResponse_Object
	//	*ExportResponse_Relation
	//	*ExportResponse_Stats
	Msg           isExportResponse_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportResponse) Reset() {
	*x = ExportResponse{}
	mi := &file_aserto_directory_reader_v4_reader_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportResponse) ProtoMessage() {}

func (x *ExportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aserto_directory_reader_v4_reader_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportResponse.ProtoReflect.Descriptor instead.
func (*ExportResponse) Descriptor() ([]byte, []int) {
	return file_aserto_directory_reader_v4_reader_proto_rawDescGZIP(), []int{23}
}

func (x *ExportResponse) GetMsg() isExportResponse_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *ExportResponse) GetManifest() *v4.Manifest {
	if x != nil {
		if x, ok := x.Msg.(*ExportResponse_Manifest); ok {
			return x.Manifest
		}
	}
	return nil
}

func (x *ExportResponse) GetModel() *v4.Model {
	if x != nil {
		if x, ok := x.Msg.(*ExportResponse_Model); ok {
			return x.Model
		}
	}
	return nil
}

func (x *ExportResponse) GetObject() *v4.Object {
	if x != nil {
		if x, ok := x.Msg.(*ExportResponse_Object); ok {
			return x.Object
		}
	}
	return nil
}

func (x *ExportResponse) GetRelation() *v4.Relation {
	if x != nil {
		if x, ok := x.Msg.(*ExportResponse_Relation); ok {
			return x.Relation
		}
	}
	return nil
}

func (x *ExportResponse) GetStats() *structpb.Struct {
	if x != nil {
		if x, ok := x.Msg.(*ExportResponse_Stats); ok {
			return x.Stats
		}
	}
	return nil
}

type isExportResponse_Msg interface {
	isExportResponse_Msg()
}

type ExportResponse_Manifest struct {
	// manifest
	Manifest *v4.Manifest `protobuf:"bytes,1,opt,name=manifest,proto3,oneof"`
}

type ExportResponse_Model struct {
	// model
	Model *v4.Model `protobuf:"bytes,2,opt,name=model,proto3,oneof"`
}

type ExportResponse_Object struct {
	// object
	Object *v4.Object `protobuf:"bytes,3,opt,name=object,proto3,oneof"`
}

type ExportResponse_Relation struct {
	// relation
	Relation *v4.Relation `protobuf:"bytes,4,opt,name=relation,proto3,oneof"`
}

type ExportResponse_Stats struct {
	// stats
	Stats *structpb.Struct `protobuf:"bytes,8,opt,name=stats,proto3,oneof"`
}

func (*ExportResponse_Manifest) isExportResponse_Msg() {}

func (*ExportResponse_Model) isExportResponse_Msg() {}

func (*ExportResponse_Object) isExportResponse_Msg() {}

func (*ExportResponse_Relation) isExportResponse_Msg() {}

func (*ExportResponse_Stats) isExportResponse_Msg() {}

var File_aserto_directory_reader_v4_reader_proto protoreflect.FileDescriptor

const file_aserto_directory_reader_v4_reader_proto_rawDesc = "" +
	"\n" +
	"'aserto/directory/reader/v4/reader.proto\x12\x1aaserto.directory.reader.v4\x1a'aserto/directory/common/v4/common.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/api/field_behavior.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"B\n" +
	"\x12GetManifestRequest\x12,\n" +
	"\x05empty\x18\x01 \x01(\v2\x16.google.protobuf.EmptyR\x05empty\"S\n" +
	"\x13GetManifestResponse\x12<\n" +
	"\x06result\x18\x01 \x01(\v2$.aserto.directory.common.v4.ManifestR\x06result\"?\n" +
	"\x0fGetModelRequest\x12,\n" +
	"\x05empty\x18\x01 \x01(\v2\x16.google.protobuf.EmptyR\x05empty\"M\n" +
	"\x10GetModelResponse\x129\n" +
	"\x06result\x18\x01 \x01(\v2!.aserto.directory.common.v4.ModelR\x06result\"\x86\x01\n" +
	"\x10GetObjectRequest\x12$\n" +
	"\vobject_type\x18\x01 \x01(\tB\x03\xe0A\x02R\n" +
	"objectType\x12 \n" +
	"\tobject_id\x18\x02 \x01(\tB\x03\xe0A\x02R\bobjectId\x12*\n" +
	"\x0ewith_relations\x18\x03 \x01(\bB\x03\xe0A\x01R\rwithRelations\"\x93\x01\n" +
	"\x11GetObjectResponse\x12:\n" +
	"\x06result\x18\x01 \x01(\v2\".aserto.directory.common.v4.ObjectR\x06result\x12B\n" +
	"\trelations\x18\x04 \x03(\v2$.aserto.directory.common.v4.RelationR\trelations\"\\\n" +
	"\x11GetObjectsRequest\x12G\n" +
	"\x05param\x18\x01 \x03(\v2,.aserto.directory.common.v4.ObjectIdentifierB\x03\xe0A\x02R\x05param\"R\n" +
	"\x12GetObjectsResponse\x12<\n" +
	"\aresults\x18\x01 \x03(\v2\".aserto.directory.common.v4.ObjectR\aresults\"\x82\x01\n" +
	"\x12ListObjectsRequest\x12$\n" +
	"\vobject_type\x18\x01 \x01(\tB\x03\xe0A\x01R\n" +
	"objectType\x12F\n" +
	"\x04page\x18\t \x01(\v2-.aserto.directory.common.v4.PaginationRequestB\x03\xe0A\x01R\x04page\"\x97\x01\n" +
	"\x13ListObjectsResponse\x12<\n" +
	"\aresults\x18\x01 \x03(\v2\".aserto.directory.common.v4.ObjectR\aresults\x12B\n" +
	"\x04page\x18\t \x01(\v2..aserto.directory.common.v4.PaginationResponseR\x04page\"\xa1\x02\n" +
	"\x12GetRelationRequest\x12$\n" +
	"\vobject_type\x18\x01 \x01(\tB\x03\xe0A\x02R\n" +
	"objectType\x12 \n" +
	"\tobject_id\x18\x02 \x01(\tB\x03\xe0A\x02R\bobjectId\x12\x1f\n" +
	"\brelation\x18\x03 \x01(\tB\x03\xe0A\x02R\brelation\x12&\n" +
	"\fsubject_type\x18\x04 \x01(\tB\x03\xe0A\x02R\vsubjectType\x12\"\n" +
	"\n" +
	"subject_id\x18\x05 \x01(\tB\x03\xe0A\x02R\tsubjectId\x12.\n" +
	"\x10subject_relation\x18\x06 \x01(\tB\x03\xe0A\x01R\x0fsubjectRelation\x12&\n" +
	"\fwith_objects\x18\a \x01(\bB\x03\xe0A\x01R\vwithObjects\"\xcd\x01\n" +
	"\x13GetRelationResponse\x12<\n" +
	"\x06result\x18\x01 \x01(\v2$.aserto.directory.common.v4.RelationR\x06result\x12:\n" +
	"\x06object\x18\x02 \x01(\v2\".aserto.directory.common.v4.ObjectR\x06object\x12<\n" +
	"\asubject\x18\x03 \x01(\v2\".aserto.directory.common.v4.ObjectR\asubject\"`\n" +
	"\x13GetRelationsRequest\x12I\n" +
	"\x05param\x18\x01 \x03(\v2..aserto.directory.common.v4.RelationIdentifierB\x03\xe0A\x02R\x05param\"V\n" +
	"\x14GetRelationsResponse\x12>\n" +
	"\aresults\x18\x01 \x03(\v2$.aserto.directory.common.v4.RelationR\aresults\"\xaf\x03\n" +
	"\x14ListRelationsRequest\x12$\n" +
	"\vobject_type\x18\x01 \x01(\tB\x03\xe0A\x01R\n" +
	"objectType\x12 \n" +
	"\tobject_id\x18\x02 \x01(\tB\x03\xe0A\x01R\bobjectId\x12\x1f\n" +
	"\brelation\x18\x03 \x01(\tB\x03\xe0A\x01R\brelation\x12&\n" +
	"\fsubject_type\x18\x04 \x01(\tB\x03\xe0A\x01R\vsubjectType\x12\"\n" +
	"\n" +
	"subject_id\x18\x05 \x01(\tB\x03\xe0A\x01R\tsubjectId\x12.\n" +
	"\x10subject_relation\x18\x06 \x01(\tB\x03\xe0A\x01R\x0fsubjectRelation\x12&\n" +
	"\fwith_objects\x18\a \x01(\bB\x03\xe0A\x01R\vwithObjects\x12B\n" +
	"\x1bwith_empty_subject_relation\x18\b \x01(\bB\x03\xe0A\x01R\x18withEmptySubjectRelation\x12F\n" +
	"\x04page\x18\t \x01(\v2-.aserto.directory.common.v4.PaginationRequestB\x03\xe0A\x01R\x04page\"\xd5\x02\n" +
	"\x15ListRelationsResponse\x12>\n" +
	"\aresults\x18\x01 \x03(\v2$.aserto.directory.common.v4.RelationR\aresults\x12X\n" +
	"\aobjects\x18\x02 \x03(\v2>.aserto.directory.reader.v4.ListRelationsResponse.ObjectsEntryR\aobjects\x12B\n" +
	"\x04page\x18\t \x01(\v2..aserto.directory.common.v4.PaginationResponseR\x04page\x1a^\n" +
	"\fObjectsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x128\n" +
	"\x05value\x18\x02 \x01(\v2\".aserto.directory.common.v4.ObjectR\x05value:\x028\x01\"\xde\x01\n" +
	"\fCheckRequest\x12$\n" +
	"\vobject_type\x18\x01 \x01(\tB\x03\xe0A\x02R\n" +
	"objectType\x12 \n" +
	"\tobject_id\x18\x02 \x01(\tB\x03\xe0A\x02R\bobjectId\x12\x1f\n" +
	"\brelation\x18\x03 \x01(\tB\x03\xe0A\x02R\brelation\x12&\n" +
	"\fsubject_type\x18\x04 \x01(\tB\x03\xe0A\x02R\vsubjectType\x12\"\n" +
	"\n" +
	"subject_id\x18\x05 \x01(\tB\x03\xe0A\x02R\tsubjectId\x12\x19\n" +
	"\x05trace\x18\a \x01(\bB\x03\xe0A\x01R\x05trace\"n\n" +
	"\rCheckResponse\x12\x14\n" +
	"\x05check\x18\x01 \x01(\bR\x05check\x12\x14\n" +
	"\x05trace\x18\x02 \x03(\tR\x05trace\x121\n" +
	"\acontext\x18\x03 \x01(\v2\x17.google.protobuf.StructR\acontext\"\x95\x01\n" +
	"\rChecksRequest\x12B\n" +
	"\adefault\x18\x01 \x01(\v2(.aserto.directory.reader.v4.CheckRequestR\adefault\x12@\n" +
	"\x06checks\x18\x02 \x03(\v2(.aserto.directory.reader.v4.CheckRequestR\x06checks\"S\n" +
	"\x0eChecksResponse\x12A\n" +
	"\x06checks\x18\x01 \x03(\v2).aserto.directory.reader.v4.CheckResponseR\x06checks\"\xb0\x02\n" +
	"\x0fGetGraphRequest\x12$\n" +
	"\vobject_type\x18\x01 \x01(\tB\x03\xe0A\x02R\n" +
	"objectType\x12 \n" +
	"\tobject_id\x18\x02 \x01(\tB\x03\xe0A\x01R\bobjectId\x12\x1f\n" +
	"\brelation\x18\x03 \x01(\tB\x03\xe0A\x02R\brelation\x12&\n" +
	"\fsubject_type\x18\x04 \x01(\tB\x03\xe0A\x02R\vsubjectType\x12\"\n" +
	"\n" +
	"subject_id\x18\x05 \x01(\tB\x03\xe0A\x01R\tsubjectId\x12.\n" +
	"\x10subject_relation\x18\x06 \x01(\tB\x03\xe0A\x01R\x0fsubjectRelation\x12\x1d\n" +
	"\aexplain\x18\a \x01(\bB\x03\xe0A\x01R\aexplain\x12\x19\n" +
	"\x05trace\x18\b \x01(\bB\x03\xe0A\x01R\x05trace\"\xab\x01\n" +
	"\x10GetGraphResponse\x12F\n" +
	"\aresults\x18\x01 \x03(\v2,.aserto.directory.common.v4.ObjectIdentifierR\aresults\x129\n" +
	"\vexplanation\x18\x02 \x01(\v2\x17.google.protobuf.StructR\vexplanation\x12\x14\n" +
	"\x05trace\x18\x03 \x03(\tR\x05trace\"d\n" +
	"\rExportRequest\x12\x18\n" +
	"\aoptions\x18\x01 \x01(\rR\aoptions\x129\n" +
	"\n" +
	"start_from\x18\x14 \x01(\v2\x1a.google.protobuf.TimestampR\tstartFrom\"\xc9\x02\n" +
	"\x0eExportResponse\x12B\n" +
	"\bmanifest\x18\x01 \x01(\v2$.aserto.directory.common.v4.ManifestH\x00R\bmanifest\x129\n" +
	"\x05model\x18\x02 \x01(\v2!.aserto.directory.common.v4.ModelH\x00R\x05model\x12<\n" +
	"\x06object\x18\x03 \x01(\v2\".aserto.directory.common.v4.ObjectH\x00R\x06object\x12B\n" +
	"\brelation\x18\x04 \x01(\v2$.aserto.directory.common.v4.RelationH\x00R\brelation\x12/\n" +
	"\x05stats\x18\b \x01(\v2\x17.google.protobuf.StructH\x00R\x05statsB\x05\n" +
	"\x03msg*\xa4\x01\n" +
	"\x06Option\x12\x12\n" +
	"\x0eOPTION_UNKNOWN\x10\x00\x12\x18\n" +
	"\x14OPTION_DATA_MANIFEST\x10\x01\x12\x15\n" +
	"\x11OPTION_DATA_MODEL\x10\x02\x12\x17\n" +
	"\x13OPTION_DATA_OBJECTS\x10\b\x12\x19\n" +
	"\x15OPTION_DATA_RELATIONS\x10\x10\x12\x0f\n" +
	"\vOPTION_DATA\x10\x18\x12\x10\n" +
	"\fOPTION_STATS\x10@2\xb9\x17\n" +
	"\x06Reader\x12\xb1\x02\n" +
	"\vGetManifest\x12..aserto.directory.reader.v4.GetManifestRequest\x1a/.aserto.directory.reader.v4.GetManifestResponse\"\xc0\x01\x92A\x9a\x01\n" +
	"\tdirectory\x12\x15Get manifest instance\x1a\x1aReturns manifest instance.* directory.reader.v4.manifest.getJ\x1d\n" +
	"\x03304\x12\x16\n" +
	"\x14Object not modified.b\x19\n" +
	"\x17\n" +
	"\x13AuthorizationHeader\x12\x00\x82\xd3\xe4\x93\x02\x1c\x12\x1a/api/v4/directory/manifest\x12\x9c\x02\n" +
	"\bGetModel\x12+.aserto.directory.reader.v4.GetModelRequest\x1a,.aserto.directory.reader.v4.GetModelResponse\"\xb4\x01\x92A\x91\x01\n" +
	"\tdirectory\x12\x12Get model instance\x1a\x17Returns model instance.*\x1ddirectory.reader.v4.model.getJ\x1d\n" +
	"\x03304\x12\x16\n" +
	"\x14Object not modified.b\x19\n" +
	"\x17\n" +
	"\x13AuthorizationHeader\x12\x00\x82\xd3\xe4\x93\x02\x19\x12\x17/api/v4/directory/model\x12\xdf\x02\n" +
	"\tGetObject\x12,.aserto.directory.reader.v4.GetObjectRequest\x1a-.aserto.directory.reader.v4.GetObjectResponse\"\xf4\x01\x92A\xb6\x01\n" +
	"\tdirectory\x12\x13Get object instance\x1a:Returns single object instance, optionally with relations.*\x1edirectory.reader.v4.object.getJ\x1d\n" +
	"\x03304\x12\x16\n" +
	"\x14Object not modified.b\x19\n" +
	"\x17\n" +
	"\x13AuthorizationHeader\x12\x00\x82\xd3\xe4\x93\x024\x122/api/v4/directory/object/{object_type}/{object_id}\x12m\n" +
	"\n" +
	"GetObjects\x12-.aserto.directory.reader.v4.GetObjectsRequest\x1a..aserto.directory.reader.v4.GetObjectsResponse\"\x00\x12\x98\x02\n" +
	"\vListObjects\x12..aserto.directory.reader.v4.ListObjectsRequest\x1a/.aserto.directory.reader.v4.ListObjectsResponse\"\xa7\x01\x92A\x82\x01\n" +
	"\tdirectory\x12\x15List object instances\x1a!Returns list of object instances.* directory.reader.v4.objects.listb\x19\n" +
	"\x17\n" +
	"\x13AuthorizationHeader\x12\x00\x82\xd3\xe4\x93\x02\x1b\x12\x19/api/v4/directory/objects\x12\xd3\x02\n" +
	"\vGetRelation\x12..aserto.directory.reader.v4.GetRelationRequest\x1a/.aserto.directory.reader.v4.GetRelationResponse\"\xe2\x01\x92A\xbc\x01\n" +
	"\tdirectory\x12\x15Get relation instance\x1a:Returns single relation instance, optionally with objects.* directory.reader.v4.relation.getJ\x1f\n" +
	"\x03304\x12\x18\n" +
	"\x16Relation not modified.b\x19\n" +
	"\x17\n" +
	"\x13AuthorizationHeader\x12\x00\x82\xd3\xe4\x93\x02\x1c\x12\x1a/api/v4/directory/relation\x12s\n" +
	"\fGetRelations\x12/.aserto.directory.reader.v4.GetRelationsRequest\x1a0.aserto.directory.reader.v4.GetRelationsResponse\"\x00\x12\xa7\x02\n" +
	"\rListRelations\x120.aserto.directory.reader.v4.ListRelationsRequest\x1a1.aserto.directory.reader.v4.ListRelationsResponse\"\xb0\x01\x92A\x89\x01\n" +
	"\tdirectory\x12\x18List relations instances\x1a#Returns list of relation instances.*\"directory.reader.v4.relations.listb\x19\n" +
	"\x17\n" +
	"\x13AuthorizationHeader\x12\x00\x82\xd3\xe4\x93\x02\x1d\x12\x1b/api/v4/directory/relations\x12\xe4\x01\n" +
	"\x05Check\x12(.aserto.directory.reader.v4.CheckRequest\x1a).aserto.directory.reader.v4.CheckResponse\"\x85\x01\x92A`\n" +
	"\tdirectory\x12\x05Check\x1a\x16Returns check outcome.*\x19directory.reader.v4.checkb\x19\n" +
	"\x17\n" +
	"\x13AuthorizationHeader\x12\x00\x82\xd3\xe4\x93\x02\x1c:\x01*\"\x17/api/v4/directory/check\x12\xf4\x01\n" +
	"\x06Checks\x12).aserto.directory.reader.v4.ChecksRequest\x1a*.aserto.directory.reader.v4.ChecksResponse\"\x92\x01\x92Al\n" +
	"\tdirectory\x12\x06Checks\x1a Returns multiple check outcomes.*\x1adirectory.reader.v4.checksb\x19\n" +
	"\x17\n" +
	"\x13AuthorizationHeader\x12\x00\x82\xd3\xe4\x93\x02\x1d:\x01*\"\x18/api/v4/directory/checks\x12\xb7\x02\n" +
	"\bGetGraph\x12+.aserto.directory.reader.v4.GetGraphRequest\x1a,.aserto.directory.reader.v4.GetGraphResponse\"\xcf\x01\x92A\x84\x01\n" +
	"\tdirectory\x12\tGet graph\x1a6Returns object graph from anchor to subject or object.*\x19directory.reader.v4.graphb\x19\n" +
	"\x17\n" +
	"\x13AuthorizationHeader\x12\x00\x82\xd3\xe4\x93\x02A\x12?/api/v4/directory/graph/{object_type}/{relation}/{subject_type}\x12c\n" +
	"\x06Export\x12).aserto.directory.reader.v4.ExportRequest\x1a*.aserto.directory.reader.v4.ExportResponse\"\x000\x01BFZDgithub.com/aserto-dev/go-directory/aserto/directory/reader/v4;readerb\x06proto3"

var (
	file_aserto_directory_reader_v4_reader_proto_rawDescOnce sync.Once
	file_aserto_directory_reader_v4_reader_proto_rawDescData []byte
)

func file_aserto_directory_reader_v4_reader_proto_rawDescGZIP() []byte {
	file_aserto_directory_reader_v4_reader_proto_rawDescOnce.Do(func() {
		file_aserto_directory_reader_v4_reader_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_aserto_directory_reader_v4_reader_proto_rawDesc), len(file_aserto_directory_reader_v4_reader_proto_rawDesc)))
	})
	return file_aserto_directory_reader_v4_reader_proto_rawDescData
}

var file_aserto_directory_reader_v4_reader_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_aserto_directory_reader_v4_reader_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_aserto_directory_reader_v4_reader_proto_goTypes = []any{
	(Option)(0),                   // 0: aserto.directory.reader.v4.Option
	(*GetManifestRequest)(nil),    // 1: aserto.directory.reader.v4.GetManifestRequest
	(*GetManifestResponse)(nil),   // 2: aserto.directory.reader.v4.GetManifestResponse
	(*GetModelRequest)(nil),       // 3: aserto.directory.reader.v4.GetModelRequest
	(*GetModelResponse)(nil),      // 4: aserto.directory.reader.v4.GetModelResponse
	(*GetObjectRequest)(nil),      // 5: aserto.directory.reader.v4.GetObjectRequest
	(*GetObjectResponse)(nil),     // 6: aserto.directory.reader.v4.GetObjectResponse
	(*GetObjectsRequest)(nil),     // 7: aserto.directory.reader.v4.GetObjectsRequest
	(*GetObjectsResponse)(nil),    // 8: aserto.directory.reader.v4.GetObjectsResponse
	(*ListObjectsRequest)(nil),    // 9: aserto.directory.reader.v4.ListObjectsRequest
	(*ListObjectsResponse)(nil),   // 10: aserto.directory.reader.v4.ListObjectsResponse
	(*GetRelationRequest)(nil),    // 11: aserto.directory.reader.v4.GetRelationRequest
	(*GetRelationResponse)(nil),   // 12: aserto.directory.reader.v4.GetRelationResponse
	(*GetRelationsRequest)(nil),   // 13: aserto.directory.reader.v4.GetRelationsRequest
	(*GetRelationsResponse)(nil),  // 14: aserto.directory.reader.v4.GetRelationsResponse
	(*ListRelationsRequest)(nil),  // 15: aserto.directory.reader.v4.ListRelationsRequest
	(*ListRelationsResponse)(nil), // 16: aserto.directory.reader.v4.ListRelationsResponse
	(*CheckRequest)(nil),          // 17: aserto.directory.reader.v4.CheckRequest
	(*CheckResponse)(nil),         // 18: aserto.directory.reader.v4.CheckResponse
	(*ChecksRequest)(nil),         // 19: aserto.directory.reader.v4.ChecksRequest
	(*ChecksResponse)(nil),        // 20: aserto.directory.reader.v4.ChecksResponse
	(*GetGraphRequest)(nil),       // 21: aserto.directory.reader.v4.GetGraphRequest
	(*GetGraphResponse)(nil),      // 22: aserto.directory.reader.v4.GetGraphResponse
	(*ExportRequest)(nil),         // 23: aserto.directory.reader.v4.ExportRequest
	(*ExportResponse)(nil),        // 24: aserto.directory.reader.v4.ExportResponse
	nil,                           // 25: aserto.directory.reader.v4.ListRelationsResponse.ObjectsEntry
	(*emptypb.Empty)(nil),         // 26: google.protobuf.Empty
	(*v4.Manifest)(nil),           // 27: aserto.directory.common.v4.Manifest
	(*v4.Model)(nil),              // 28: aserto.directory.common.v4.Model
	(*v4.Object)(nil),             // 29: aserto.directory.common.v4.Object
	(*v4.Relation)(nil),           // 30: aserto.directory.common.v4.Relation
	(*v4.ObjectIdentifier)(nil),   // 31: aserto.directory.common.v4.ObjectIdentifier
	(*v4.PaginationRequest)(nil),  // 32: aserto.directory.common.v4.PaginationRequest
	(*v4.PaginationResponse)(nil), // 33: aserto.directory.common.v4.PaginationResponse
	(*v4.RelationIdentifier)(nil), // 34: aserto.directory.common.v4.RelationIdentifier
	(*structpb.Struct)(nil),       // 35: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil), // 36: google.protobuf.Timestamp
}
var file_aserto_directory_reader_v4_reader_proto_depIdxs = []int32{
	26, // 0: aserto.directory.reader.v4.GetManifestRequest.empty:type_name -> google.protobuf.Empty
	27, // 1: aserto.directory.reader.v4.GetManifestResponse.result:type_name -> aserto.directory.common.v4.Manifest
	26, // 2: aserto.directory.reader.v4.GetModelRequest.empty:type_name -> google.protobuf.Empty
	28, // 3: aserto.directory.reader.v4.GetModelResponse.result:type_name -> aserto.directory.common.v4.Model
	29, // 4: aserto.directory.reader.v4.GetObjectResponse.result:type_name -> aserto.directory.common.v4.Object
	30, // 5: aserto.directory.reader.v4.GetObjectResponse.relations:type_name -> aserto.directory.common.v4.Relation
	31, // 6: aserto.directory.reader.v4.GetObjectsRequest.param:type_name -> aserto.directory.common.v4.ObjectIdentifier
	29, // 7: aserto.directory.reader.v4.GetObjectsResponse.results:type_name -> aserto.directory.common.v4.Object
	32, // 8: aserto.directory.reader.v4.ListObjectsRequest.page:type_name -> aserto.directory.common.v4.PaginationRequest
	29, // 9: aserto.directory.reader.v4.ListObjectsResponse.results:type_name -> aserto.directory.common.v4.Object
	33, // 10: aserto.directory.reader.v4.ListObjectsResponse.page:type_name -> aserto.directory.common.v4.PaginationResponse
	30, // 11: aserto.directory.reader.v4.GetRelationResponse.result:type_name -> aserto.directory.common.v4.Relation
	29, // 12: aserto.directory.reader.v4.GetRelationResponse.object:type_name -> aserto.directory.common.v4.Object
	29, // 13: aserto.directory.reader.v4.GetRelationResponse.subject:type_name -> aserto.directory.common.v4.Object
	34, // 14: aserto.directory.reader.v4.GetRelationsRequest.param:type_name -> aserto.directory.common.v4.RelationIdentifier
	30, // 15: aserto.directory.reader.v4.GetRelationsResponse.results:type_name -> aserto.directory.common.v4.Relation
	32, // 16: aserto.directory.reader.v4.ListRelationsRequest.page:type_name -> aserto.directory.common.v4.PaginationRequest
	30, // 17: aserto.directory.reader.v4.ListRelationsResponse.results:type_name -> aserto.directory.common.v4.Relation
	25, // 18: aserto.directory.reader.v4.ListRelationsResponse.objects:type_name -> aserto.directory.reader.v4.ListRelationsResponse.ObjectsEntry
	33, // 19: aserto.directory.reader.v4.ListRelationsResponse.page:type_name -> aserto.directory.common.v4.PaginationResponse
	35, // 20: aserto.directory.reader.v4.CheckResponse.context:type_name -> google.protobuf.Struct
	17, // 21: aserto.directory.reader.v4.ChecksRequest.default:type_name -> aserto.directory.reader.v4.CheckRequest
	17, // 22: aserto.directory.reader.v4.ChecksRequest.checks:type_name -> aserto.directory.reader.v4.CheckRequest
	18, // 23: aserto.directory.reader.v4.ChecksResponse.checks:type_name -> aserto.directory.reader.v4.CheckResponse
	31, // 24: aserto.directory.reader.v4.GetGraphResponse.results:type_name -> aserto.directory.common.v4.ObjectIdentifier
	35, // 25: aserto.directory.reader.v4.GetGraphResponse.explanation:type_name -> google.protobuf.Struct
	36, // 26: aserto.directory.reader.v4.ExportRequest.start_from:type_name -> google.protobuf.Timestamp
	27, // 27: aserto.directory.reader.v4.ExportResponse.manifest:type_name -> aserto.directory.common.v4.Manifest
	28, // 28: aserto.directory.reader.v4.ExportResponse.model:type_name -> aserto.directory.common.v4.Model
	29, // 29: aserto.directory.reader.v4.ExportResponse.object:type_name -> aserto.directory.common.v4.Object
	30, // 30: aserto.directory.reader.v4.ExportResponse.relation:type_name -> aserto.directory.common.v4.Relation
	35, // 31: aserto.directory.reader.v4.ExportResponse.stats:type_name -> google.protobuf.Struct
	29, // 32: aserto.directory.reader.v4.ListRelationsResponse.ObjectsEntry.value:type_name -> aserto.directory.common.v4.Object
	1,  // 33: aserto.directory.reader.v4.Reader.GetManifest:input_type -> aserto.directory.reader.v4.GetManifestRequest
	3,  // 34: aserto.directory.reader.v4.Reader.GetModel:input_type -> aserto.directory.reader.v4.GetModelRequest
	5,  // 35: aserto.directory.reader.v4.Reader.GetObject:input_type -> aserto.directory.reader.v4.GetObjectRequest
	7,  // 36: aserto.directory.reader.v4.Reader.GetObjects:input_type -> aserto.directory.reader.v4.GetObjectsRequest
	9,  // 37: aserto.directory.reader.v4.Reader.ListObjects:input_type -> aserto.directory.reader.v4.ListObjectsRequest
	11, // 38: aserto.directory.reader.v4.Reader.GetRelation:input_type -> aserto.directory.reader.v4.GetRelationRequest
	13, // 39: aserto.directory.reader.v4.Reader.GetRelations:input_type -> aserto.directory.reader.v4.GetRelationsRequest
	15, // 40: aserto.directory.reader.v4.Reader.ListRelations:input_type -> aserto.directory.reader.v4.ListRelationsRequest
	17, // 41: aserto.directory.reader.v4.Reader.Check:input_type -> aserto.directory.reader.v4.CheckRequest
	19, // 42: aserto.directory.reader.v4.Reader.Checks:input_type -> aserto.directory.reader.v4.ChecksRequest
	21, // 43: aserto.directory.reader.v4.Reader.GetGraph:input_type -> aserto.directory.reader.v4.GetGraphRequest
	23, // 44: aserto.directory.reader.v4.Reader.Export:input_type -> aserto.directory.reader.v4.ExportRequest
	2,  // 45: aserto.directory.reader.v4.Reader.GetManifest:output_type -> aserto.directory.reader.v4.GetManifestResponse
	4,  // 46: aserto.directory.reader.v4.Reader.GetModel:output_type -> aserto.directory.reader.v4.GetModelResponse
	6,  // 47: aserto.directory.reader.v4.Reader.GetObject:output_type -> aserto.directory.reader.v4.GetObjectResponse
	8,  // 48: aserto.directory.reader.v4.Reader.GetObjects:output_type -> aserto.directory.reader.v4.GetObjectsResponse
	10, // 49: aserto.directory.reader.v4.Reader.ListObjects:output_type -> aserto.directory.reader.v4.ListObjectsResponse
	12, // 50: aserto.directory.reader.v4.Reader.GetRelation:output_type -> aserto.directory.reader.v4.GetRelationResponse
	14, // 51: aserto.directory.reader.v4.Reader.GetRelations:output_type -> aserto.directory.reader.v4.GetRelationsResponse
	16, // 52: aserto.directory.reader.v4.Reader.ListRelations:output_type -> aserto.directory.reader.v4.ListRelationsResponse
	18, // 53: aserto.directory.reader.v4.Reader.Check:output_type -> aserto.directory.reader.v4.CheckResponse
	20, // 54: aserto.directory.reader.v4.Reader.Checks:output_type -> aserto.directory.reader.v4.ChecksResponse
	22, // 55: aserto.directory.reader.v4.Reader.GetGraph:output_type -> aserto.directory.reader.v4.GetGraphResponse
	24, // 56: aserto.directory.reader.v4.Reader.Export:output_type -> aserto.directory.reader.v4.ExportResponse
	45, // [45:57] is the sub-list for method output_type
	33, // [33:45] is the sub-list for method input_type
	33, // [33:33] is the sub-list for extension type_name
	33, // [33:33] is the sub-list for extension extendee
	0,  // [0:33] is the sub-list for field type_name
}

func init() { file_aserto_directory_reader_v4_reader_proto_init() }
func file_aserto_directory_reader_v4_reader_proto_init() {
	if File_aserto_directory_reader_v4_reader_proto != nil {
		return
	}
	file_aserto_directory_reader_v4_reader_proto_msgTypes[23].OneofWrappers = []any{
		(*ExportResponse_Manifest)(nil),
		(*ExportResponse_Model)(nil),
		(*ExportResponse_Object)(nil),
		(*ExportResponse_Relation)(nil),
		(*ExportResponse_Stats)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_aserto_directory_reader_v4_reader_proto_rawDesc), len(file_aserto_directory_reader_v4_reader_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_aserto_directory_reader_v4_reader_proto_goTypes,
		DependencyIndexes: file_aserto_directory_reader_v4_reader_proto_depIdxs,
		EnumInfos:         file_aserto_directory_reader_v4_reader_proto_enumTypes,
		MessageInfos:      file_aserto_directory_reader_v4_reader_proto_msgTypes,
	}.Build()
	File_aserto_directory_reader_v4_reader_proto = out.File
	file_aserto_directory_reader_v4_reader_proto_goTypes = nil
	file_aserto_directory_reader_v4_reader_proto_depIdxs = nil
}
