name: ci

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      proto_ref:
      proto_sha:
  push:
    branches:
      - main
      - v*
    # Publish `v1.2.3` tags as releases.
    tags:
      - v*
  # Run tests for PRs
  pull_request:

env:
  VAULT_ADDR: https://vault.eng.aserto.com/
  BUF_REPO: "buf.build/aserto-dev/directory"

  BUF_VERSION: "1.34.0"
  BUF_BETA_SUPPRESS_WARNINGS: 1
  PROTO_VERSION: "v0.31.7"
  GO_VERSION: "1.22"
  GO_LANGCI_LINT_VERSION: "v1.56.2"
  GO_TESTSUM_VERSION: "1.11.0"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    -
      name: Read Configuration
      uses: hashicorp/vault-action@v3
      id: vault
      with:
        url: ${{ env.VAULT_ADDR }}
        token: ${{ secrets.VAULT_TOKEN }}
        secrets: |
          kv/data/github    "USERNAME"          | GH_USERNAME;
          kv/data/github    "READ_WRITE_TOKEN"  | GH_TOKEN;
          kv/data/buf.build "ASERTO_BUF_USER"   | BUF_USER;
          kv/data/buf.build "ASERTO_BUF_TOKEN"  | BUF_TOKEN;
    -
      name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}
    -
      name: Setup buf
      uses: bufbuild/buf-setup-action@v1
      with:
        version: ${{ env.BUF_VERSION }}
        github_token: ${{ github.token }}
        buf_user: ${{ steps.vault.outputs.BUF_USER }}
        buf_api_token: ${{ steps.vault.outputs.BUF_TOKEN}}
    -
      name: Delete generated code
      run: |
        rm -rf ./aserto
    -
      name: Buf Generate
      run: |
        echo "${{ env.BUF_REPO }}:${{ env.PROTO_VERSION }}"
        buf generate ${{ env.BUF_REPO }}:${{ env.PROTO_VERSION }}
    -
      name: Lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: ${{ env.GO_LANGCI_LINT_VERSION }}
        args: --timeout=30m
    -
      name: Test Setup
      uses: gertd/action-gotestsum@v3.0.0
      with:
        gotestsum_version: ${{ env.GO_TESTSUM_VERSION }}
    -
      name: Test
      run: |
        gotestsum --format short-verbose -- -count=1 -parallel=1 -v -timeout=240s -coverprofile=cover.out -coverpkg=./... ./...
    -
      name: Commit changes
      if: github.event_name == 'workflow_dispatch'
      uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
        add: 'aserto'
