---
name: ci

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      proto_ref:
      proto_sha:
  push:
    branches:
      - main
    # Publish `v1.2.3` tags as releases.
    tags:
      - v*
  # Run tests for PRs
  pull_request:

env:
  BUF_REPO: "buf.build/aserto-dev/directory"
  BUF_VER: 1.73.0
  GO_LANGCI_LINT_VER: 2.14.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/create-github-app-token@v3
        id: app-token
        with:
          client-id: ${{ vars.CODEGEN_APP_ID }}
          private-key: ${{ secrets.CODEGEN_APP_KEY }}
      -
        name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}
      -
        name: Setup Go
        uses: actions/setup-go@v7
        with:
          go-version-file: 'go.mod'
          cache: true
      -
        name: Install toolchain
        run: |
          make deps
      -
        name: Lint
        run: |
          make lint
      -
        name: Test
        run: |
          make test
