syntax = "proto3";

package aserto.directory.model.v3;

import "google/api/field_behavior.proto";
import "google/protobuf/empty.proto";
import "google/protobuf/struct.proto";
import "google/protobuf/timestamp.proto";

option go_package = "github.com/aserto-dev/go-directory/aserto/directory/model/v3;model";

// Directory Model Service
service Model {
  // get manifest instance
  rpc GetManifest(GetManifestRequest) returns (stream GetManifestResponse) {
    option deprecated = true;
  }

  // set manifest instance
  rpc SetManifest(stream SetManifestRequest) returns (SetManifestResponse) {
    option deprecated = true;
  }

  // delete manifest instance
  rpc DeleteManifest(DeleteManifestRequest) returns (DeleteManifestResponse) {
    option deprecated = true;
  }
}

message GetManifestRequest {
  // empty request
  google.protobuf.Empty empty = 1;
}

message GetManifestResponse {
  oneof msg {
    // Manifest metadata
    Metadata metadata = 1;
    // Manifest content
    Body body = 2;
    // Model
    google.protobuf.Struct model = 3;
  }
}

message SetManifestRequest {
  // manifest instance
  oneof msg {
    // Manifest content
    Body body = 1;
  }
}

message SetManifestResponse {
  // empty result
  google.protobuf.Empty result = 1;
}

message DeleteManifestRequest {
  // empty request
  google.protobuf.Empty empty = 1;
}

message DeleteManifestResponse {
  // empty result
  google.protobuf.Empty result = 1;
}

message Metadata {
  // last updated timestamp (UTC)
  google.protobuf.Timestamp updated_at = 21 [(google.api.field_behavior) = OUTPUT_ONLY];
  // object instance etag
  string etag = 23 [(google.api.field_behavior) = OUTPUT_ONLY];
}

message Body {
  // manifest content
  bytes data = 2;
}
